### ISSUE TITLE
Input is ignored after switching tabs

### ISSUE THREAD

**Issue by metasprite** [vscode-neovim/vscode-neovim#643] opened 2021-05-19 19:34 UTC
When switching tabs, there is a slight (but very noticeable and annoying) delay before input is allowed. Inputs are ignored until after this delay. During this delay, the cursor does not flash, and the word under the cursor isn't highlighted. The cursor starts flashing and word highlighting appears at the same time input is allowed again. Using the mouse to switch tabs instead of ctrl+tab still causes this delay, but it's ever-so-slightly shorter.

Still happens with a blank `init.vim`.

**Comment by inspmoore** [comment] 2021-05-20 13:28
+1 to that!
sometimes the input freezes completely. I cannot enter insert mode, movements don't work. I have to reenable the plugin to unfreeze it.

**Comment by asvetliakov** [comment] 2021-05-31 18:49
@inspmoore workaround is to switch a tab in current editor pane and switch back

**Comment by cupcakearmy** [comment] 2022-04-24 11:44
I get random freezes which are insanely anoying unfortunately xD
Can I help somehow? It seems quite random, have not found a "pattern" yet.

**Comment by theol0403** [comment] 2022-04-30 05:13
Try to find a pattern and make a new issue. Unfortunately, the issue is due to nvim loading and can only be fixed by general performance gains.

**Closed by theol0403** 2022-04-30 05:13 UTC
