### ISSUE TITLE
bug:  characters shaking when input Chinese

### ISSUE THREAD

**Issue by zwyyy456** [vscode-neovim/vscode-neovim#1936] opened 2024-05-04 02:40 UTC
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

v0.9.5

### Operating system/version

14.4.1

### Describe the bug

当我启用了 vscode.neovim 插件，并在 vscode 中输入中文时，中文输入的候选框以及该行的中文字符会发生颤抖现象，当我选择不启用该插件之后，就不会再出现该问题了。

When I enable the vscode.neovim plugin and type in Chinese characters in Visual Studio Code, the candidate list for Chinese input and the Chinese characters in the current line start shaking. However, when I disable the plugin, the issue no longer occurs.

### Steps To Reproduce

Just input Chinese on Mac. It seems this problem doesn't appear on windows.

https://github.com/vscode-neovim/vscode-neovim/assets/45388797/2ea2bf51-053e-4e44-bf18-3c62b839c4c9

The problem is as the video shows.

### Expected Behavior

I hope won't disappear.

**Comment by zwyyy456** [comment] 2024-05-04 04:55
The latest version without this problem is `1.10.1`。

**Comment by xiyaowong** [comment] 2024-05-04 05:27
Duplicate of #1921

**Closed by xiyaowong** 2024-05-04 05:27 UTC
Labels: bug
