### ISSUE TITLE
Map both kj and jk to escape.

### ISSUE THREAD

**Issue by bradleybauer** [vscode-neovim/vscode-neovim#258] opened 2020-05-07 15:35 UTC
Hey all, thank you for the great extension.
Is it possible to map both jk and kj to escape to normal mode?
I have tried
```
      {
        "command": "vscode-neovim.compositeEscape1",
        "key": "j",
        "when": "neovim.mode == insert",
        "args": "j"
      },
      {
        "command": "vscode-neovim.compositeEscape2",
        "key": "k",
        "when": "neovim.mode == insert",
        "args": "k"
    },
    {
        "command": "vscode-neovim.compositeEscape3",
        "key": "k",
        "when": "neovim.mode == insert",
        "args": "k"
      },
      {
        "command": "vscode-neovim.compositeEscape4",
        "key": "j",
        "when": "neovim.mode == insert",
        "args": "j"
    },
```
Which does not work.
Also, using `compositeEscape1` and `compositeEscape2` instead of `compositeEscape3` and `compositeEscape4` does not work.

**Comment by bradleybauer** [comment] 2020-08-25 17:54
> #245 explains how to do this.
@IgorGee  that issue does not solve my problem. I want both jk and kj mapped at the same time. But I am only able to get either jk or kj mapped but not both. Were you able to get this to work?

**Comment by IgorGee** [comment] 2020-08-25 21:40
Sorry, I misread. I was only interested in getting `kj` to work.

**Comment by fiveNinePlusR** [comment] 2021-01-19 01:37
I'd also like to have this feature... i press jk and kj at the same time and let whichever one i press first win out. faster and less error prone than jk or kj or even jj

**Comment by fiveNinePlusR** [comment] 2021-01-19 21:02
a low effort patch to make this feature work would be to enable the timer in the second function which would have the outcome where `jj` `jk` `kj` and `kk` all escape. i don't think kk happens often in english so that's acceptable for me. as it stands when you bind k to the second function it will escape on `jj` and `jk` so this feature change is not that far off current behavior. 

Also, i suppose a really low effort way to do it is to document the fact that you can bind j and k to the first command to get that same outcome as above. 

adding a datestamp here would solve that https://github.com/asvetliakov/vscode-neovim/blob/master/src/typing_manager.ts#L163

same code as https://github.com/asvetliakov/vscode-neovim/blob/master/src/typing_manager.ts#L150

a more involved patch similar to how spacemacs does it with evil-escape would be taking a chord string as a setting which would be any two letters and then having a memory of which key was pressed and when and compare it to the chord and have a boolean if symmetric bindings exit from insert. so `"jk"` is the chord and if the boolean is false only jk would exit and if the boolean is true allow `"kj"` to exit as well. I guess it depends on how rigid you want to be in the final outcome and inputs.

**Comment by theol0403** [comment] 2022-04-28 00:41
Duplicate of #563.

**Closed by theol0403** 2022-04-28 00:41 UTC
Labels: enhancement
