### ISSUE TITLE
`C-f` and `C-b` stopped working in 0.0.93

### ISSUE THREAD

**Issue by chrisands** [vscode-neovim/vscode-neovim#1064] opened 2022-10-25 22:23 UTC
When try to scroll with shortcuts it doesn't scroll by page, only by line. In `nvim` everything works fine and when I install `0.0.92` also works fine. 
```
$ nvim -v
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey
```

**Comment by chrisands** [comment] 2022-10-25 22:25
It may be related to https://github.com/vscode-neovim/vscode-neovim/issues/983

**Comment by nokia-git** [comment] 2022-10-26 00:28
there is another issue, that M did not work when cursor is out of window.
M should move cursor to middle of window, but it failed on version 0.93

**Comment by LihaoLikeOrangeJuice** [comment] 2022-10-27 04:56
Same issue. But C-d and C-u still work. By the way, my neovim's version is 0.7.2.

**Comment by theol0403** [comment] 2022-10-28 01:15
Yes, oops, https://github.com/vscode-neovim/vscode-neovim/commit/468b0710e8972fe11e312733d1eac12aa550eea4 was not supposed to be released. It was in master but I wasn't going to release until https://github.com/vscode-neovim/vscode-neovim/pull/993 is merged. 
I accidentally released with the mouse select hotfix.

**Comment by introom** [comment] 2022-10-30 13:24
WIll the comannd 
```
            {
                "command": "vscode-neovim.ctrl-d",
                "title": "Neovim: ctrl-d"
            },
```
be bought back in future releases ?

**Comment by plai2010** [comment] 2022-11-03 19:01
Thanks @theol0403 for pointing out the cause. I downgraded to 0.92 for now.

**Comment by theol0403** [comment] 2022-11-12 23:34
The change has been reverted and released. The reverted code will be bundled with #993.

**Closed by theol0403** 2022-11-12 23:34 UTC
