### ISSUE TITLE
[Bug] vscode-neovim runs pasted code after hitting `Esc` ???!!!

### ISSUE THREAD

**Issue by wenfangdu** [vscode-neovim/vscode-neovim#1185] opened 2023-03-24 08:41 UTC
Repro Steps:

1. Create a file named `test.vim`.
2. Paste `map <leader> <cmd>call VSCodeNotifyVisual('editor.action.commentLine', 0)<cr><esc>` into the file.
3. Use VSCode to open it.
4. Enter insert mode.
5. Use `Cmd+A` to select all.
6. Use `Cmd+C` to copy.
7. Use `Cmd+V` to paste.
8. Hit `Esc`.
9. The current line gets commented out!!!!!!

**Comment by wenfangdu** [comment] 2023-03-24 08:52
This is the strangest bug I've seen recently, can you reproduce it? @justinmk

**Comment by archilkarchava** [comment] 2023-03-24 17:28
I've also encountered this issue and created a [pull request with the fix](https://github.com/vscode-neovim/vscode-neovim/pull/1167) a couple of weeks ago. However, the tests are failing on Windows, and I cannot investigate the reason as I do not have a Windows machine.

**Comment by justinmk** [comment] 2023-03-25 10:58
duplicate of #1182  ?

**Comment by wenfangdu** [comment] 2023-03-25 12:04
@justinmk No, I've been using `extensions.experimental.affinity` since it first came out.

**Closed** 2023-10-05 14:28 UTC
Labels: bug, manager: document_change
