### ISSUE TITLE
Visual mode rendering error

### ISSUE THREAD

**Issue by ahmadshiddiq** [vscode-neovim/vscode-neovim#966] opened 2022-07-09 08:08 UTC
![image](https://user-images.githubusercontent.com/53107961/178097404-82a5f4b5-7268-4135-8b26-820994f2644d.png)

When I change mode it `visual` mode some text will looks like image on above, I've try to disable nvim on vscode and the try to block some code but there nothing problem. Did anyone can help me to fix this stuff?

Thank you!

fact: the text is not actually changed, after back to `normal` mode or other mode the text will back as usual.

**Comment by ahmadshiddiq** [comment] 2022-07-09 08:21
this bug is not show in version `0.0.84`

**Comment by theol0403** [comment] 2022-08-11 20:52
Duplicate of #968

**Closed by theol0403** 2022-08-11 20:52 UTC
