### ISSUE TITLE
Unable to init vscode-neovim: nvim_call_function: Vim(call):E5555: API call: Invalid buffer id: 3

### ISSUE THREAD

**Issue by Damaged-Code** [vscode-neovim/vscode-neovim#903] opened 2022-05-13 08:17 UTC
I dont know why when i install vscodeneovim and reload window it will show this errro and then I cant normal to use this vscode-neovim

**Comment by Damaged-Code** [comment] 2022-05-13 09:11
<img width="484" alt="image" src="https://user-images.githubusercontent.com/26178326/168251486-0084febe-2469-4c1e-86d1-dcf732f8bf09.png">

**Comment by Damaged-Code** [comment] 2022-05-13 09:17
<img width="473" alt="image" src="https://user-images.githubusercontent.com/26178326/168252682-b063165f-8104-4607-9e74-550f21eb6d86.png">

**Comment by justinmk** [comment] 2022-05-13 12:47
duplicate of https://github.com/vscode-neovim/vscode-neovim/issues/833

**Closed by justinmk** 2022-05-13 12:47 UTC
