### ISSUE TITLE
bug: Brother啊！Neovim was disconnected啊!

### ISSUE THREAD

**Issue by chenhui2016** [vscode-neovim/vscode-neovim#2186] opened 2024-07-26 08:38 UTC
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

0.10.0 

### Operating system/version

Ubuntu 22.04/24.04

### Describe the bug

If I **don't leave** the editor interface, no error will be reported for a long time. Once I **leave** the editor interface (such as opening jupyter/copilot chat/vscode minimized), **Neovim was disconnected** will appear. I set the json code about neovim in the setting as follows:
``"vscode-neovim.neovimExecutablePaths.linux": "/opt/nvim-linux64/bin/nvim",     
  "extensions.experimental.affinity": {
    "asvetliakov.vscode-neovim": 1
  },``

如果我一直在editor界面**不离开**，多久都不会报错，一但我**离开**editor界面（如打开jupyter/copilot chat/vscode最小化）就会出现Neovim was disconnected。我在setting中设置了关于neovim的json代码如下所示：
``"vscode-neovim.neovimExecutablePaths.linux": "/opt/nvim-linux64/bin/nvim",     
  "extensions.experimental.affinity": {
    "asvetliakov.vscode-neovim": 1
  },``  

我谷歌翻译的不知道意思正确吗，所以为了方便你查看，这是原文。

### Steps To Reproduce

``"vscode-neovim.neovimExecutablePaths.linux": "/opt/nvim-linux64/bin/nvim",     
  "extensions.experimental.affinity": {
    "asvetliakov.vscode-neovim": 1
  },``  

### Expected Behavior

Please solve this problem, because it is impossible to stay in the editor interface without leaving.

请解决这个问题，因为不可能一直在editor界面不离开。

**Comment by xiyaowong** [comment] 2024-07-26 12:50
Duplicate of #2165. This issue will be alleviated in the next version.

**Closed by xiyaowong** 2024-07-26 12:50 UTC
Labels: bug
