### ISSUE TITLE
[Bug] Unexpected output panel popping up

### ISSUE THREAD

**Issue by wenfangdu** [vscode-neovim/vscode-neovim#954] opened 2022-07-03 11:37 UTC
When using vim-easymotion with `map f <plug>(easymotion-s2)`, the output panel shows up every time the user presses `f`:

![image](https://user-images.githubusercontent.com/28700378/177037734-87073dd4-c490-4163-b0d3-0b874d0ee5ef.png)

VSCode Neovim: v0.0.87

**Comment by theol0403** [comment] 2022-07-03 17:51
Duplicate of https://github.com/vscode-neovim/vscode-neovim/issues/910

**Closed** 2022-07-03 17:51 UTC

**Comment by justinmk** [comment] 2022-07-04 10:12
Is there not an EasyMotion option that tells it to shutup?

**Comment by wenfangdu** [comment] 2022-07-04 11:04
@justinmk `let g:EasyMotion_prompt = ""`
