### ISSUE TITLE
How to change VSCode (extension) setting parameter on enter/exit insert mode?

### ISSUE THREAD

**Issue by yanshay** [vscode-neovim/vscode-neovim#852] opened 2022-04-05 19:10 UTC
I want to change a setting of some VSCode extension when entering and exiting insert mode. I searched and couldn't find a way to do that.

I am aware it is possible to use VSCodeNotify/Call from a vim command to call vscode functions but couldn't find how to use that to change a setting. Preferably I'd like the setting to change just for the session and not persist, but even if it would persist it would be better than nothing.

Is it doable?

**Comment by harrisonmg** [comment] 2022-04-22 14:50
It looks like the extension API supports updating config values via the `update()` function: https://code.visualstudio.com/api/references/vscode-api#WorkspaceConfiguration

You could make a very simple extension / modify this extension to add a vscode command that calls that function, and then call that command via `VSCodeNotify`.

I know "make a new extension" is not very helpful, but to answer your question yes it certainly seems possible.

**Comment by theol0403** [comment] 2022-04-30 05:10
Duplicate of #796

**Closed by theol0403** 2022-04-30 05:10 UTC
