### ISSUE TITLE
Focus jumps to latest position when 2 tabs are open side by side

### ISSUE THREAD

**Issue by QAston** [vscode-neovim/vscode-neovim#642] opened 2021-05-18 16:37 UTC
Same issue and behaviour as #427 but for editors opened in side-by-side tabs

**Comment by QAston** [comment] 2021-07-30 21:28
Turns out this is caused by my config workaround for #613

**Comment by QAston** [comment] 2021-07-30 23:19
Actually, the issue is due to the fact that the plugin updates the cursor position from neovim in insert mode, which it shouldn't do.

**Comment by justinmk** [comment] 2022-04-30 22:16
> the plugin updates the cursor position from neovim in insert mode, which it shouldn't do.

Sounds like something that should be fixed. Adding new options (https://github.com/vscode-neovim/vscode-neovim/pull/716) doesn't fix that root cause.

**Comment by QAston** [comment] 2022-05-01 10:54
There are reason why the plugin doesn't post updates for insert mode - mainly performance and having a consistent method of keeping things in sync. Lack of consistency gives you stuff like this.

**Comment by theol0403** [comment] 2022-10-12 16:37
Duplicate of https://github.com/vscode-neovim/vscode-neovim/issues/776

**Closed by theol0403** 2022-10-12 16:37 UTC
