### ISSUE TITLE
bug: clicking through global search activates `VISUAL` mode

### ISSUE THREAD

**Issue by Adnios** [vscode-neovim/vscode-neovim#1828] opened 2024-02-25 13:23 UTC
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

NVIM v0.9.4

### Operating system/version

Windows 11

### Describe the bug

When jumping from global search, VISUAL mode is automatically activated.
![issue](https://github.com/vscode-neovim/vscode-neovim/assets/41060790/ce9351c3-0411-4f4d-80b5-f4f96926f92f)

### Steps To Reproduce

1. click global search results
2. hit enter key to jump to text
3. visual mode is activated 

### Expected Behavior

Cursor should jump in the editor in NORMAL mode.

**Comment by theol0403** [comment] 2024-02-26 01:14
Duplicate of https://github.com/vscode-neovim/vscode-neovim/issues/1738

**Closed** 2024-02-26 01:14 UTC
Labels: bug
