### ISSUE TITLE
binding "jk" breaks typing Russian 

### ISSUE THREAD

**Issue by slavugan** [vscode-neovim/vscode-neovim#545] opened 2021-01-31 20:35 UTC
I have binded "gj" for switching to command mode 
` {
        "command": "vscode-neovim.compositeEscape1",
        "key": "g",
        "when": "neovim.mode == insert && editorTextFocus",
        "args": "g"
    },
    {
        "command": "vscode-neovim.compositeEscape2",
        "key": "j",
        "when": "neovim.mode == insert && editorTextFocus",
        "args": "j"
    }
`
and when I'm typing in Russian, instead of "п" or "р" editor types "g" or "j" accordingly.

**Comment by Lopol2010** [comment] 2021-04-11 06:43
yes please fix this is annoying bug:(

**Comment by eyehol3** [comment] 2021-05-20 09:29
did you find a solution?

**Comment by slavugan** [comment] 2021-05-20 11:57
yes, switched back to **vscodevim** :)

**Comment by theol0403** [comment] 2022-04-28 00:47
Duplicate of #653

**Closed by theol0403** 2022-04-28 00:47 UTC
