### ISSUE TITLE
Word is shifted to the right when cursor over

### ISSUE THREAD

**Issue by olalonde** [vscode-neovim/vscode-neovim#1096] opened 2022-12-12 16:18 UTC
Any idea what is causing this and how to fix it?

https://user-images.githubusercontent.com/416585/207097346-3e777195-08a3-4984-9453-df875da76ad1.mov

**Comment by olalonde** [comment] 2022-12-12 16:26
I tried disabling all my Neovim settings and plugins in `init.lua` but the issue persists:


https://user-images.githubusercontent.com/416585/207098895-030a91c6-e4e2-4d77-9b04-b4dc8d4cb75c.mov

**Comment by olalonde** [comment] 2022-12-12 16:27
```
 nvim --version
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.1/share/nvim"
```

**Comment by theol0403** [comment] 2022-12-13 19:14
Probably caused by https://github.com/vscode-neovim/vscode-neovim/pull/1083

**Comment by theol0403** [comment] 2022-12-13 19:26
Do you have tabs in your file?

Might be fixed by efforts in https://github.com/vscode-neovim/vscode-neovim/pull/1099/files

**Comment by ctstacey** [comment] 2022-12-16 01:57
(off topic)  @olalonde what program are you using for screen capture?  Thanks in advance.

**Comment by theol0403** [comment] 2022-12-30 01:23
Fixed by https://github.com/vscode-neovim/vscode-neovim/pull/1099

**Closed by theol0403** 2022-12-30 01:23 UTC

**Comment by olalonde** [comment] 2023-01-02 04:40
> (off topic) @olalonde what program are you using for screen capture? Thanks in advance.

I think I just used the built one in MacOS (cmd+shift+5)
