### ISSUE TITLE
Newline acting weirdly

### ISSUE THREAD

**Issue by rbits0** [vscode-neovim/vscode-neovim#1098] opened 2022-12-13 05:43 UTC
When I press o to create a newline, it creates it with 6 and a half indents for some reason in this file. This doesn't happen when I press enter while in insert mode. Also only happens after line 9.

![vscode-neovim](https://user-images.githubusercontent.com/56014573/207237503-90cd0880-d144-4157-89d0-70c4722d17dd.gif)

Also doesn't happen if I change the '[' to another character.

**Comment by guyguy2001** [comment] 2022-12-13 11:55
Does it happen if you do this in neovim itself?

**Comment by rbits0** [comment] 2022-12-13 12:18
No

**Comment by theol0403** [comment] 2022-12-13 19:15
- upgrade nvim to latest version
- try installing some older versions of vscode-neovim to see if the issue is recent
- try with no nvim init.vim

**Comment by rbits0** [comment] 2023-01-01 12:08
I am on the latest vscode-neovim version, with an empty init.vim. The problem does not occur on vscode-neovim 0.52 and below. Version 0.61 is the first vscode-neovim version that this problem occurs in. To reproduce the problem, create a python file with only this line:
```python
if '[':
```

I am using nvim 0.8.0 on KDE Neon 5.26, and VSCode 1.74.2

**Comment by theol0403** [comment] 2023-07-05 00:09
Duplicate of https://github.com/vscode-neovim/vscode-neovim/issues/799

**Closed by theol0403** 2023-07-05 00:09 UTC
Labels: need more info, can't reproduce
