### ISSUE TITLE
bug: in any other vscode extension, console.time (and some other console methods) error

### ISSUE THREAD

**Issue by sadan4** [vscode-neovim/vscode-neovim#2253] opened 2024-09-19 00:19 UTC
### Check the following:

- [X] I have tried setting `vscode-neovim.neovimClean` in VSCode settings and **restarting VSCode.**
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing (closed!) issues.

### Neovim version (nvim -v)

NVIM v0.10.1

### Operating system/version

Linux 6.11

### Problem (including [log messages](https://github.com/vscode-neovim/vscode-neovim?tab=readme-ov-file#troubleshooting))

I was recently working on another vscode extension. while trying to use the console.time function, I run into this error with only vscode-neovim installed. if I uninstall vscode-neovim, it goes away

```
TypeError: Cannot read properties of undefined (reading 'apply')
	at console.<computed> [as time] (/home/[my username]/.vscode/extensions/asvetliakov.vscode-neovim-1.18.7/dist/extension.js:2:159285)
```

### Steps To Reproduce

install vscode-neovim

start an extension with run and debug

attempt to run `console.time` in a vscode extension

see error in debug console

### Expected Behavior

console.time works as expected

**Comment by justinmk** [comment] 2024-09-19 08:17
What version of vscode-neovim are you using? This is a duplicate of https://github.com/vscode-neovim/vscode-neovim/issues/2242 . It should have been fixed by https://github.com/neovim/node-client/pull/395 , which was included in vscode-neovim v1.18.12

**Comment by sadan4** [comment] 2024-09-19 19:58
ah, i am on 1.18.2

**Comment by justinmk** [comment] 2024-09-19 20:21
> ah, i am on 1.18.2

You mean https://github.com/vscode-neovim/vscode-neovim/releases/tag/v1.18.2 , 10 releases ago? Why are you on such an old version?

It is not possible to fix bugs if you don't update the software.

**Closed** 2024-09-19 20:21 UTC
Labels: bug

**Comment by sadan4** [comment] 2024-09-19 20:29
> > ah, i am on 1.18.2
> 
> You mean [`v1.18.2` (release)](https://github.com/vscode-neovim/vscode-neovim/releases/tag/v1.18.2) , 10 releases ago? Why are you on such an old version?
> 
> It is not possible to fix bugs if you don't update the software.

I am on this version as this is the last version that is supported by vscode 1.89.1
