### ISSUE TITLE
issue: Dead greek key does not work with keybinds

### ISSUE THREAD

**Issue by eekhof** [vscode-neovim/vscode-neovim#1466] opened 2023-09-20 00:05 UTC
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

v0.9.2

### Operating system/version

254.3-1-arch

### Describe the bug

VSCode Neovim version: v0.6.1

I have enabled the dead greek key to be able to type greek letters quickly as a combination of CTRL+latin letter with

```xmodmap -e "keycode 105 = dead_greek dead_greek dead_greek dead_greek"```

This works as expected on all text fields in my system. In VSCode however, when I add the lines

```
{
 "command": "vscode-neovim.compositeEscape1",
 "key": "j",
 "when": "neovim.mode == insert && editorTextFocus",
 "args": "j"
},
{
 "command": "vscode-neovim.compositeEscape2",
 "key": "k",
 "when": "neovim.mode == insert && editorTextFocus",
 "args": "k"
},
```

to my keybindings.json, so as to use the jk-combination to return to normal mode (which works fine as of itself), the j-key in combination with the CTRL-key will not produce "θ" anymore as it is supposed to, but just "j".

Can this be fixed, or is it in the nature of VSCode's keybindings that this is broken? And if so, is there a viable workaround?

Best, thanks,
Lucas

### Steps To Reproduce

1. `xmodmap -e "keycode 105 = dead_greek dead_greek dead_greek dead_greek"` (Get proper key ID with  `xev | grep keycode`)
2. Add keybindings to VSCode keybindings.json:
```
{
 "command": "vscode-neovim.compositeEscape1",
 "key": "j",
 "when": "neovim.mode == insert && editorTextFocus",
 "args": "j"
},
{
 "command": "vscode-neovim.compositeEscape2",
 "key": "k",
 "when": "neovim.mode == insert && editorTextFocus",
 "args": "k"
},
```
3. Open VSCode Neovim, in insert mode type CTRL+j

### Expected Behavior

Dead greek key + j should make "θ" appear in VSCode Neovim, but "j" appears instead.

**Comment by theol0403** [comment] 2023-09-20 01:52
I think this might be duplicate of another issue, can you try to find it

**Comment by eekhof** [comment] 2023-09-20 02:59
> I think this might be duplicate of another issue, can you try to find it

Oh sorry, I thought I had looked, I will search again

**Comment by ShamanValius** [comment] 2024-04-25 06:42
with your settings vs code

> Добавьте привязки клавиш в VSCode keybindings.json:

and my settings keymaps.lua

`vim.keymap.set("i", "jk", "<ESC>", { noremap = true, silent = true }) `

this combination works

**Closed** 2024-04-30 23:55 UTC
Labels: bug, help wanted, category: localisation, manager: typing
