### ISSUE TITLE
Convert VSCode selection to visual mode selection

### ISSUE THREAD

**Issue by pokey** [vscode-neovim/vscode-neovim#553] opened 2021-02-13 09:02 UTC
I know there's a way to go from visual mode selection to VSCode selection, but I was wondering if there's any command to go the other direction. I spend most of my time in insert mode, but would like to be able to use things like vim-abolish on my VSCode selection. Having a command to convert a VSCode selection to a visual mode selection would make such a task straightforward

**Comment by robclancy** [comment] 2021-03-29 23:52
The fact it doesn't do this automatically basically makes this extension unusable for me.

**Comment by yogeshdhamija** [comment] 2021-10-03 14:06
This may be a duplicate of https://github.com/asvetliakov/vscode-neovim/issues/395 (though I grant that your title is better). 

There is a PR open to (ostensibly) fix it, though it hasn't been merged yet.

**Comment by theol0403** [comment] 2022-01-19 06:54
Duplicate of #395

**Comment by theol0403** [comment] 2022-08-04 16:59
Since that issue is closed, no longer a duplicate.

**Closed** 2023-07-21 20:54 UTC
Labels: category: visual, category: sync, priority, manager: cursor
