### ISSUE TITLE
ctrl+e and ctrl+y does not work with numbers to repeat

### ISSUE THREAD

**Issue by russoue** [vscode-neovim/vscode-neovim#729] opened 2021-08-16 19:59 UTC
Not sure if I am describing it clearly but when I try to do `5 ctrl+y` instead of moving 5 lines I see only 1 line moving.  The behavior is the same for `ctrl+e`.  Basically the number I specify to repeat the command is ignored.  I am running version `v0.0.82` in Mac OS.  Please take a look.

**Comment by theol0403** [comment] 2022-04-29 04:26
Duplicate of #361

**Closed by theol0403** 2022-04-29 04:26 UTC
