### ISSUE TITLE
Cursor unable to jump correctly during substituting

### ISSUE THREAD

**Issue by unlsycn** [vscode-neovim/vscode-neovim#1121] opened 2023-01-03 04:26 UTC
![output](https://user-images.githubusercontent.com/31343548/210298942-37a2b1c6-1c7d-4311-abf8-e60b6c89cc36.gif)
In preceding video, the cursor can jump to the substitutions when I type `/old`. In contrast, it is unable to jump over the screen when I use `:%s/old/new/gc`.

**Comment by snacksncode** [comment] 2023-01-07 14:33
I also noticed this and would like to know how hard it is to add this feature

**Comment by theol0403** [comment] 2023-07-05 07:58
Duplicate of https://github.com/vscode-neovim/vscode-neovim/issues/1149

**Closed by theol0403** 2023-07-05 07:58 UTC
