### ISSUE TITLE
Can't seem to get Vim syntax highlighting to work

### ISSUE THREAD

**Issue by tylanphear** [vscode-neovim/vscode-neovim#785] opened 2021-12-11 21:24 UTC
I know, I know. The plugin doesn't support Vim syntax highlighting, but I work in a programming language ([Stanza](http://lbstanza.org)) that has generally poor syntax highlighting support, and wanted to take advantage of a [Vim syntax highlighting plugin](https://github.com/tylanphear/stanza.vim) that I wrote. For a number of reasons, it's non-trivial to rewrite this into a VS Code textmate grammar, and in theory using this extension it should be possible to leverage the existing Vim syntax plugin.

I was able to get past the initial hurdle (the syntax engine was disabled) by making changes to `vim/vscode-options.vim` and `vim/vscode-neovim.vim` to remove the `setlocal syntax=off` commands there. This seemed to re-enable the syntax engine and I was then able to see syntax highlighting groups being applied to the text.

However, I can't seem to get the next step working: actually seeing the syntax groups highlighted on my screen, as evidenced by the following screenshot showing that the highlight groups exist, but are not being colored correctly:
![Screenshot from 2021-12-11 12-25-46](https://user-images.githubusercontent.com/30333819/145691820-301947aa-5066-44db-8b20-c5c620e78737.png)

Everywhere that *isn't* highlighted is part of a syntax group, which should be getting highlighted according to Vim's highlight groups. I figured at first that this was due to misconfiguration of the extension's settings, in particular `vscode-neovim.highlightGroups.highlights`. However, attempts to get the highlighting to work there were not fruitful. Things I tried:

1. Manually listing each Vim base syntax group with `"vim"` as the color (e.g. `"Comment": { "color": "vim" }`)
2. Manually listing each Vim base syntax group with an arbitrary color (e.g. `"Comment": { "color": "#00AA00" }`)
3. Manually listing each Stanza syntax group with `"vim"` as the color (e.g. `"stanzaComment": { "color": "vim" }`)
4. Manually listing each Stanza syntax group with an arbitrary color (e.g. `"stanzaComment": { "color": "#00AA00" }`)

I also tried setting `vscode-neovim.highlightGroups.unknownHighlight` to `"vim"` and also an arbitrary color, neither seemed to work there either.

Anyways, this report is starting to get long. I would really like to see being possible to achieve with `vscode-neovim`. If that is indeed the case, and if it would be in the realm of interest of the maintainers, I would be more than willing to contribute/maintain enough to get this working, if need be.

**Comment by theol0403** [comment] 2021-12-21 19:04
I think you might need to add `"vscode-neovim.highlightGroups.ignoreHighlights": [],` to your settings as well for this to work.

**Comment by tylanphear** [comment] 2021-12-22 10:07
That was an excellent suggestion! Thanks to your help, I am now able to see the highlighting groups applied. However, there are still a few issues that I haven't been able to sort out yet:

1. The highlighting does not appear when the document is initially loaded. Highlighting seems to only be triggered by some event that forces a redraw of the text, like selecting it in visual mode or jumping to the end of the file.
![Highlighting only appears upon selection](https://user-images.githubusercontent.com/30333819/147074525-2030e1a9-27f4-4db7-8790-b36a9cbdc830.png)
2. Highlighting of inserted text is performed correctly, but not during insertion. In particular, when editing an item that is already highlighted, the current highlighting is applied to inserted text until the insertion event ends (i.e. switch back to normal mode occurs.)
During insertion:
![Highlighting is erroneously continued during insertion](https://user-images.githubusercontent.com/30333819/147075067-e7d8e2ac-b4e2-4f8a-8a69-2779a4ce9d4e.png)
After insertion:
![Highlighting is only corrected after insertion event ends](https://user-images.githubusercontent.com/30333819/147075075-84230f3b-c60a-4c8f-bff6-7c1e388d6a1e.png)

Still, very pleased to see this beginning to work!

**Comment by theol0403** [comment] 2022-01-03 20:18
Looks good! Unfortunately, I can't see any good solution to this. This extension, by design, does not update neovim during insert mode. This is to mitigate the typing lag that occurs when vscode extensions bind the `type` event, and this can only be fixed by vscode devs. You could try to disable the mechanism that disconnects neovim in insert mode, but that would not be ideal.

For the first issue, you might be able to fix it with an autocommand on buffer load that forces a redraw.

**Comment by theol0403** [comment] 2022-04-30 03:48
Closing as this isn't supported by the plugin. However, feel free to update with any progress you've made.

**Closed by theol0403** 2022-04-30 03:48 UTC

**Comment by theol0403** [comment] 2022-10-12 03:08
@tylanphear if this is still relevant for you, https://github.com/vscode-neovim/vscode-neovim/pull/992 updates insert mode highlighting in realtime which could fix your problem

**Comment by pnck** [comment] 2023-07-16 08:17
@theol0403 

Hi, I'm facing problems similar to this issue.

I am currently working with `ragel`, using an official syntax file that works perfectly in `vim/neovim` : https://github.com/adrian-thurston/ragel/blob/master/ragel.vim

Now I want to enable the same highlighting capabilities in `vscode`. Since `vscodevim` is a just partial simulation of `vim`, I turned to use `vscode-neovim` and hope it would leverage the complete features from `neovim`. I found this issue that seems to meet my case during searching.

Could you offer some more detailed instructions on _how to utilize the `neovim` builtin highlighting in `vscode`_ ?

**Comment by theol0403** [comment] 2023-07-16 18:56
@pnck it won't be ideal, but:
- clear ignored highlights list in settings 
- make a custom build of vscode-neovim that removes `syntax off` in settings.vim (two lines in there).

**Comment by pnck** [comment] 2023-07-17 08:12
@theol0403 thanks. but the highlight rendering is still a bit glitchy 🤔 I'd put it aside.

**Comment by theol0403** [comment] 2023-07-17 15:22
Yeah it's not perfect at the moment.
