### ISSUE TITLE
Send VSCode visual selections

### ISSUE THREAD

**Issue by hholst80** [vscode-neovim/vscode-neovim#172] opened 2020-02-09 08:33 UTC
While using Live Share I noticed that visual selections in Neovim does not show up as proper selections on the other side, in the same way that mouse selections does.

Is it possible to get selections made in neovim visual and via commands such as visual-inner-word (viw) to show up in a consistent way?

**Comment by asvetliakov** [comment] 2020-02-09 08:43
unfortunately no, until there will be an api in neovim to provide visual mode enter/left and especially changed events, see https://github.com/neovim/neovim/issues/4399 . 

theortically/as workaround you can try to use `call VSCodeNotifyRange/VSCodeNotifyRangePos(...)` from neovim side to produce vscode selection. Theoretically you can try to call it in something like `autocmd CursorMoved` (check current mode by calling `mode()`). Currently, `VSCodeNotify` requires vscode command as first argument but you might to try to pass empty `""` here

**Comment by hholst80** [comment] 2020-02-10 17:09
I appreciate that you knew so well what needed to be in place for this to happen.

I'll not hold my breath that this will be fixed any time soon:

> bsmith89 opened this issue on Mar 3, 2016

**Comment by asvetliakov** [comment] 2020-02-11 07:42
>I'll not hold my breath that this will be fixed any time soon:

I believe neovim team is aware of such API needs and they're planning to improve current GUI protocol for own-rendering clients such as vscode-neovim, so this may happen in very nearest future

**Comment by jli** [comment] 2021-07-22 19:47
> theortically/as workaround you can try to use call VSCodeNotifyRange/VSCodeNotifyRangePos(...) from neovim side to produce vscode selection. Theoretically you can try to call it in something like autocmd CursorMoved (check current mode by calling mode()). Currently, VSCodeNotify requires vscode command as first argument but you might to try to pass empty "" here

Would you be able to be more explicit about how to do this workaround? I'm not super familiar w/ neovim configuration.

(I've been enjoying vscode-neovim a lot, but this issue hampers my workflow a lot, so would be very eager to try a workaround.)

**Comment by theol0403** [comment] 2022-04-30 03:31
The linked issue has been fixed! Now there is nvim api for mode changed. Hopefully this means the visual mode workaround can be fixed and selections can be sent to vscode!

**Comment by theol0403** [comment] 2022-04-30 03:34
Related: #7

**Comment by robclancy** [comment] 2022-05-30 09:25
Why is this closed? The neovim issue is fixed now too.

**Comment by theol0403** [comment] 2022-08-04 17:19
I did some more digging, and made a reopen request here: https://github.com/neovim/neovim/issues/11590

Related:
https://github.com/vscode-neovim/vscode-neovim/issues/172
https://github.com/vscode-neovim/vscode-neovim/issues/778

Basically, the workarounds that were used before were:
- whenever cursor pos updated
- if mode is visual
	- if mode didn't used to be visual, make a marker 
	- make a selection from marker to cursor pos (smart, based on visual mode)

This was bad, didn't support `o` to change anchor, and only triggered on cursor move, not visual mode selection (viw didn't work). 

Another option is to parse `Visual` highlight group. But this is limited to viewport, so will produce incorrect large selections. 

We now have ModeChanged, so we know when to start and stop showing visual mode. We just need to know when to update. It is possible that we can use `getpos('v')` to find full-range visual highlight, but we still need to know when to update.

**Comment by theol0403** [comment] 2022-08-11 22:43
The goal of this change is to improve lots of behavior (minimap, liveshare, vscode commands, disable line highlight, etc), and remove a lot of useless code (vscode range commands, visual sync workarounds, visual sync bindings, etc). 

While waiting for https://github.com/neovim/neovim/issues/19708, I started working on this. I figured I could make something that almost works perfectly by checking visual mode on CursorMoved or if the `Visual` highlight updates, which leaves only the situation where the selection won't update if visual is changed outside of viewport without cursor moving. 

However, I have run into a fundamental issue, which was here from the beginning. The problem is that neovim and vscode treat selections differently. In neovim, if the selection is `|one|`, with `|e|` being the location of the cursor, then the whole word is selected. However, in vscode, the selection is `|one|e`. This means that any selection will be missing the last character. This breaks C-S-F and vscode commands, requiring workarounds, removing the whole point of this change. 

The way vscode works is that the "primary selection" will always contain the cursor. But vscode also reads the primary selection for commands. Therefore, we can't set the cursor to the right place (`on|e|`) without making the selection (`|on|e`).

This is also experienced in https://github.com/VSCodeVim/Vim/issues/1755.

The only solution is to hide the vscode cursor, and then render a fake cursor as a decoration. This is done in VSCodeVim https://github.com/VSCodeVim/Vim/pull/1862. 

This is a slightly larger refactor, but should be possible.

**Comment by theol0403** [comment] 2023-06-30 07:50
Finally making some progress again!

![](https://imgur.com/a/sxEZ3wu.png)

https://imgur.com/a/sxEZ3wu

**Comment by theol0403** [comment] 2023-07-03 09:59
I've been making a bunch of progress, PR incoming.

I'm just writing down my thoughts. My biggest challenge right now is figuring out where the fake cursor highlight should come from.

Three options:
- cursor manager owns a fake cursor
  - style is either manually defined, or copied from vim's visual cursor decoration options
- cursor manager borrows highlight manager's cursor decorator
  - problem is if the decorator wants to be used as a highlight and a fake cursor
- show the cursor as a highlight, using the highlight manager, by sending the highlight from vim

I'm currently leaning towards the last option, which involves adding some autocommands that update the fake cursor from the neovim side.

**Closed** 2023-07-21 20:54 UTC
Labels: enhancement, category: visual, category: sync, priority, manager: cursor, manager: highlight

**Comment by trkoch** [comment] 2023-07-31 12:35
This is great! Thank you.
