### ISSUE TITLE
Working directory not set correctly with WSL installation

### ISSUE THREAD

**Issue by jrpear** [vscode-neovim/vscode-neovim#520] opened 2021-01-09 22:56 UTC
Right now, `:pwd` gives me `/mnt/c/<user>/AppData/Local/Programs/Microsoft VSCode` in every document and workspace. I think the working directory should actually be the current workspace, to match the behavior of VSCode's integrated terminal.

I'm using a Neovim installation on WSL. The working directory is the same regardless of whether I open a file in WSL or Windows.

**Comment by theol0403** [comment] 2021-01-09 22:59
Humm, for what it's worth, on linux the working directory is properly set, thanks to #429. I guess there is a bug with WSL.

**Comment by asvetliakov** [comment] 2021-01-09 23:05
PR is welcome here

**Comment by jpear1** [comment] 2021-01-18 05:08
Possibly relate, I get this error in VSCode Neovim output on boot:
```
E344: Can't find directory "home<user><workingdirectory>" in cdpath
E484: Can't open file $MYVIMRC
```
E344 has been anonymized, basically it's the working directory with no slashes.

**Comment by Hugo-Matias** [comment] 2021-04-29 19:39
Experiencing the same behavior as @jpear1, either on a remote launched from a wsl bash with `code /some/path` or launching a local instance via powershell or cmd.
Since I don't see any noticeable negative effects from the error, for the time being, is there a way to suppress specific errors from triggering the output panel? It pops up and takes focus every time I open vscode.

**Comment by m42martin** [comment] 2021-11-27 00:46
Bump.  I'm getting the same message as @jrpear. VSCode is connected to wsl remote session.

**Comment by sisrfeng** [comment] 2022-01-16 10:58
+1
![image](https://user-images.githubusercontent.com/53520949/149657116-57342c2d-9cb8-4d6a-9779-a513f9017b84.png)

**Comment by jsonMartin** [comment] 2022-03-11 21:33
I'm also experiencing this error...does this error directly affect usability at all?

**Comment by Hugo-Matias** [comment] 2022-03-11 21:57
> I'm also experiencing this error...does this error directly affect usability at all?

I still have it and until today is just a minor nuisance on startup, don't think i've run into any problem because of this. It would be nice if we could get rid of the error but I think we can safely ignore it.

**Comment by jaron-l** [comment] 2022-03-30 12:52
I might be wrong in assuming this is the same issue but this appears to also happen in any remote connection in vscode. I have the same problem on linux when I use VSCode's remote extension to ssh into another machine. `!pwd` returns the local path with the local user instead of using the remote user and directory of the workspace that VSCode is using. This also affects any file open or edit commands. It displays the working directory of the local user and path.

**Comment by mikkelti** [comment] 2022-04-15 17:27
> I'm also experiencing this error...does this error directly affect usability at all?

It really bugs me when trying to open a file in a split view, i.e., `:sp <filename>`.

**Comment by jackblackevo** [comment] 2022-05-20 07:03
Hi, after upgraded to version [0.0.85](https://github.com/vscode-neovim/vscode-neovim/blob/master/CHANGELOG.md#0085), that always prompt the message below when VSCode start:

```
Error detected while processing command line:
E344: Can't find directory "home<my-user-name><my-vscode-project-path>" in cdpath
E472: Command failed
```

**Comment by theol0403** [comment] 2022-05-20 22:14
> Hi, after upgraded from version 0.0.84 to [0.0.85](https://github.com/vscode-neovim/vscode-neovim/blob/master/CHANGELOG.md?rgh-link-date=2022-05-20T07%3A03%3A14Z#0085), that always prompt the message below when VSCode start:
> 
> ```
> Error detected while processing command line:
> E344: Can't find directory "home<my-user-name><my-vscode-project-path>" in cdpath
> E472: Command failed
> ```
> 
> My VSCode infomation:
> 
> Version: 1.67.2 (user setup) Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5 Date: 2022-05-17T18:15:52.058Z Electron: 17.4.1 Chromium: 98.0.4758.141 Node.js: 16.13.0 V8: 9.8.177.13-electron.0 OS: Windows_NT x64 10.0.22000
> 
> Neovim-0.6.1@Ubuntu-20.04@WSL2

Humm, my guess is that the issue was always there, but #881 is displaying it for you. I have no idea what is causing that - you sure you don't have anything weird in your configs? I can't find `my-vscode-project-path` in this plugin.

@mikkelti :sp was broken for another reason, and should be fixed by latest commit. Now, it looks in your workspace for files before looking for absolute files.

**Comment by theol0403** [comment] 2022-05-20 22:29
Okay, the issue is caused by #429. Basically, in certain situations, the `workspaceFolder[0].uri.fsPath` is *not* something that can be directly `cd``'d to in neovim (vscode remote path, windows path but nvim is in wsl, etc). 

Either: 
- revert #429
- add logic that handles all possible `fsPath` combinations, and ignores impossible paths before sending to nvim 

Help wanted!

**Comment by AndysonDK** [comment] 2022-05-24 16:36
Yeah I got the same issue as @jackblackevo:
```
TypeError: Cannot read properties of undefined (reading 'getProjectForFile')
    at C1e.handleDidOpenOrSaveNotification (/home/<name>/.vscode-server/extensions/graphql.vscode-graphql-0.4.6/out/server/index.js:567:5308)
    at async /home/<name>/.vscode-server/extensions/graphql.vscode-graphql-0.4.6/out/server/index.js:602:54431
[Error - 6:31:14 PM] Connection to server got closed. Server will not be restarted.
[Info  - 6:31:14 PM] The graphql server has stopped running
```

**Comment by wenfangdu** [comment] 2022-06-12 03:22
To revert:

![image](https://user-images.githubusercontent.com/28700378/173212886-31120be7-2f4e-4120-9d72-8bf657fbdf06.png)

**Comment by Wesztman** [comment] 2022-06-21 09:00
I can confirm that downgrading the extension to 0.0.84 fixes the issue :) thanks @wenfangdu !

**Comment by theol0403** [comment] 2022-06-27 01:44
Error should be fixed in latest version.

However, the original issue (pwd not set in WSL) remains.

**Comment by unlsycn** [comment] 2023-02-26 17:33
So..Is there a way to get current file path in vimscript (with WSL installation)?

**Closed** 2023-12-09 13:43 UTC
Labels: bug, help wanted, good first issue, category: wsl, manager: main
