### ISSUE TITLE
Normal mode commands get stuck in notebook cell

### ISSUE THREAD

**Issue by rndxx** [vscode-neovim/vscode-neovim#756] opened 2021-10-21 12:21 UTC
Sometimes normal mode commands get stuck. Only thing I can do is to enter the insert mode using i and edit. Everything else freezes.

**Comment by tbenthompson** [comment] 2021-11-21 23:18
I'll second this. 

I'm not how to get trapped in these "confused" state, but sometimes I will enter a cell either by selecting it using "Enter" or by clicking on the cell and the editor will be confused:
- Normal mode commands like "j" or "k" do nothing. They don't insert a character or move the cursor. 
- The only thing that works is entering insert mode using "i" (or "a" or something else that enters insert mode). 
- Then, after entering insert mode, I can exit from insert mode and everything is fine again. 

I apologize for not having a precise way of replicating the bug. All I have is the that this seems to happen more often with large notebooks or with notebooks that haven been open a long time.

**Comment by zurdavid** [comment] 2021-12-06 15:28
Same here. I can reproduce it by pressing Ctrl-w either not followed by another key or any key that doesn't belong to a mapping, (like "v", "s").

**Comment by theol0403** [comment] 2022-04-29 05:00
New keybindings should help. Maybe the issue was it was getting stuck outside the cell without focusing the editor.

**Comment by tbenthompson** [comment] 2022-08-05 22:39
Just wanted to say that I'm still running into this issue. Less often that I used to, but it's normally once or twice a day that a notebook cell just gets into some invalid state. My workaround is to cut the cell and then paste it. This seems to reset the vscode-neovim state for the cell and all is well again.

**Comment by datacubeR** [comment] 2023-06-11 04:44
I second this. I have noticed that if a I move to a split window or change to a different tab and then comeback de cursor looks like this | (instead of the typical block). I need to go to insert mode and then comeback to make it work as usual. 

Hopefully this could be solved.

**Comment by xiyaowong** [comment] 2023-10-17 17:36
It’s best to provide a screen recording

**Comment by xiyaowong** [comment] 2023-10-23 11:18
> I second this. I have noticed that if a I move to a split window or change to a different tab and then comeback de cursor looks like this | (instead of the typical block). I need to go to insert mode and then comeback to make it work as usual.
> 
> Hopefully this could be solved.

The issue should rarely occur now, and even if it does, it's still not a big deal. See #1454

**Comment by xiyaowong** [comment] 2023-10-23 11:26
It feels like this issue may have already been fixed, as I have never encountered such a problem (except  the cursor style), and there doesn't seem to be any other feedback either. Let's close it for now, and if there are any problems, we can address them later

**Closed by xiyaowong** 2023-10-23 11:26 UTC
Labels: bug, manager: cursor
