### ISSUE TITLE
Split window cursor retains its original position

### ISSUE THREAD

**Issue by ozimos** [vscode-neovim/vscode-neovim#404] opened 2020-10-12 09:51 UTC
when using vscode with split editors, a mouse click on the text in an inactive editor pane will cause the cursor to jump to the last position of the cursor for that file. How do I get the cursor to remain exactly where I clicked

**Comment by Shatur95** [comment] 2020-10-12 10:35
Can't reproduce, I think that the problem caused by your plugins or settings.

**Comment by ozimos** [comment] 2020-10-12 17:08
Here is a gif of the cursor behaviour
http://g.recordit.co/6w1kyaobc1.gif
![neovim_cursor](https://user-images.githubusercontent.com/27624208/95773130-cfcf1100-0cb5-11eb-9327-2e25798e1ad7.gif)

**Comment by Shatur95** [comment] 2020-10-12 17:10
Seems that issue cause by your extensions or settings.

**Comment by ozimos** [comment] 2020-10-12 17:16
my vscode extensions https://gist.github.com/ozimos/93ac4fee174511a845897c2b8188bcb0 

I have removed all extensions except neovim and settings sync

**Comment by Shatur95** [comment] 2020-10-12 17:17
Try to remove all settings / Neovim settings to find out what causes the problem.

**Comment by ozimos** [comment] 2020-10-12 17:36
I am on NVIM v0.5.0-91109ff. I have removed my init.vim but the problem persists

**Comment by davetorbeck** [comment] 2020-10-15 00:03
This is also happening to me. The offending plugin is Prettier which unfortunately is essential to my workflow.  Shame because I really thought this plugin was the answer to my VSCode vim woes.

**Comment by asvetliakov** [comment] 2020-10-15 00:07
Anyone with this problem has `Mouse selection start visual mode` turned on?

**Comment by DamnWidget** [comment] 2020-10-19 14:10
I also experience this behavior, I can confirm that before using neovim dev versions this didn't happened, also disabling `Mouse selection start visual mode` does not solved the issue, if you are in insert mode and click (or Ctrl+<number>) your way out of the focused panel the cursor jumps around to the last known `NORMAL` mode position of the caret

**Comment by gjulianm** [comment] 2020-11-05 11:16
I have exactly the same problem: when in insert mode, if I switch to another panel with the mouse the cursor goes to the last normal mode position in that pane.

I tried with all extensions disabled except for Neovim, with `Mouse selection start visual mode` disabled. I have been able to reproduce this issue with NVIM v0.5.0-672-gd8e6a0396 and NVIM v0.5.0-808-gee3acef38, but only with the Neovim extension version being 0.0.61 or higher.

**Comment by asvetliakov** [comment] 2020-12-28 22:21
Can't reproduce with #461

**Comment by gjulianm** [comment] 2022-09-15 14:28
Hello,

I would like to repoen this issue because I've seen this bug propping up again, tested on a clean VSCode with no extensions other than VSCode Neovim enabled.

Versions:

VSCode:

Version: 1.71.1
Commit: e7f30e38c5a4efafeec8ad52861eb772a9ee4dfb
Date: 2022-09-08T19:41:58.611Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.5.0
Sandboxed: No

NeoVim extension: v0.0.89
nvim version: NVIM v0.7.2

I've tried and again reverting to versions <0.0.60 (0.0.52 for example) of the extension fixes this. I've tested other versions to help locate where the failure was happening:

- 0.0.82: present
- 0.0.80: present
- 0.0.72: not present
- 0.0.78: present
- 0.0.75: present
- 0.0.74: present
- 0.0.73: not present

So it looks like it was a change introduced in 0.0.74 that reintroduced this bug. I'm attaching a video demonstrating the problem

[bugneovimvscode.webm](https://user-images.githubusercontent.com/1334568/190430365-d550d60d-c764-4788-9e32-f0e4e599f6b6.webm)

**Comment by theol0403** [comment] 2022-09-23 17:04
@gjulianm can you try with #993

**Comment by gjulianm** [comment] 2022-09-26 09:32
I tried with that branch (more specifically, commit 6757f39ee12e7fc6850d8dcb91a759fbc8e31052) and the behavior is still there, but funnily enough it now happens on the other editor :D See on the video attached how the cursor jumps in the left editor when I click the right one
[bugneovimvscode_2.webm](https://user-images.githubusercontent.com/1334568/192243155-8b8476f8-b574-41ed-bfda-86ab902ac6d4.webm)

**Comment by theol0403** [comment] 2022-10-21 21:49
Should be fixed by https://github.com/vscode-neovim/vscode-neovim/pull/1050

**Closed by theol0403** 2022-10-21 21:49 UTC
Labels: bug

**Comment by gjulianm** [comment] 2022-10-24 07:43
I tested with that branch and I can confirm that the behavior doesn't happen anymore. Thank you very much!
