### ISSUE TITLE
More generic composite key escape method (e.g. for jj/jk/kj etc)

### ISSUE THREAD

**Issue by BlueDrink9** [vscode-neovim/vscode-neovim#563] opened 2021-03-02 01:23 UTC
## The problem

Currently the [composite key system](https://github.com/asvetliakov/vscode-neovim/blob/ff0082fc0234f069c8cf0983dab9d5820ad9869a/src/typing_manager.ts#L142) is a little strange. In order to handle the case where the two letters are the same (eg `jj`), the first composite key has to trigger an escape if it sees its bound key again. This means handling the case where they are different (eg `kj`) will always also handle the case where they are the same (i.e. `kk` as well as `kj`). Also, it only allows for one combination, so would not allow order-independent mapping of the `kj` chord (i.e. trigger on both `kj` and `jk`

## Proposed solution (WIP)

Have a single function to be mapped to, something like `compositeEscNotifyKeyPressed`. All keys within the chord, whether just `j` or both `k` and `j` should be mapped to this individually, so you might end up with something like:

```
{
    "key": "j",
    "args": "j",
    "command": "vscode-neovim.compositeEscNotifyKeyPressed",
    "when": "neovim.mode == insert && editorTextFocus"
},
{
    "key": "k",
    "args": "k",
    "command": "vscode-neovim.compositeEscNotifyKeyPressed",
    "when": "neovim.mode == insert && editorTextFocus"
}
```

This would be accompanied with a separate option (say, "`compositeEscKeyChords`"), a dictionary holding each chord you want to bind, for example:

```
{
    "k": "v",
    "v": "k",
    "j": "j"
    // Not supported with this algorithm because of the duplicate key:
    // "v": "k"
}
```

Then the callback function should store as a variable the pressed key (passed as an arg) if it is in `compositeEscKeyChords` as a key. If that variable already has something in it, and the current press is within the timeout, check to see if the current press is a value in the map for the stored previous key. If so, do the backspace and esc. If not, send the character.

What do you think about this setup? As far as I can see it would solve the problems above, and do so in a more elegant way than the current solution.

(I think the timeout should also be provided as an option, because people can get quite sensitive about their `timeoutlen` in vim.)

**Comment by ChasKane** [comment] 2022-05-03 10:24
#892 My stab at this; works for me but could be more robust.

**Comment by ChasKane** [comment] 2022-06-05 11:48
Ok I implemented a version of this, updated tests, etc. It's general enough to map any key, or just one if you include `escOnDoubleTap: true` in the args list in `keybindings.json`. Also added `timeoutLen` arg!

**Comment by theol0403** [comment] 2022-07-05 15:24
https://github.com/vscode-neovim/vscode-neovim/pull/886#issuecomment-1175189763

**Comment by BlueDrink9** [comment] 2022-11-30 02:52
I believe #886 being merged is sufficient to resolve this issue. Big thanks to theol0403

**Comment by theol0403** [comment] 2022-11-30 02:54
Sorry, I don't think it is. I think in the final released version, the native jk functionality was scrapped because it caused problems.

**Comment by theol0403** [comment] 2022-11-30 03:13
@BlueDrink9 thanks for your comments, but I think the alternate method is fundamentally broken. 

It is possible that some of the more recent prs fixed it.

But I think the problem is with lag. If you type a sentence rapidly with j or k in it, the j and k might be typed in the wrong location.

**Comment by BlueDrink9** [comment] 2022-11-30 03:18
Ah, I see what you mean. In the tests I had been using it for, I hadn't needed to type those keys so I didn't notice the delay :/

Bother

**Comment by awilkins** [comment] 2024-01-17 11:29
Is this the same feature as e.g. composites for surround like

`gza` (I'm using LazyVim which [remaps mini.surround](https://www.lazyvim.org/plugins/coding#minisurround) prefix to `gz` (but doesn't seem to document this very well....) ?

A minor gripe I have is that the code as written gives you (I think) 1/5th of a second to complete each key in the sequence, which means if you have to think about it (as you do when learning), you lose the "thread".

In contrast LazyVim gives you all the time in the world and a nice helper too (see below).

You have to get as far as `gza` quite rapidly ; I  often do `gz` then stall for a moment while I try to remember which of the seven choices you have for this plugin is next. The help sheet would be LOVELY (but probably out of scope for this thread), but the time to think or look away at a cheat sheet would be even lovelier ; which would presumably mean changing this to a purely state-driven sequence and not having the composite timestamp checks in `typing_manager.ts` (which is my best guess at what causes this behaviour ..?)

---

`g` - goto

![image](https://github.com/vscode-neovim/vscode-neovim/assets/368399/d7e8646b-66d7-48a8-9c3c-2d6fad661d37)

`z` - surround

![image](https://github.com/vscode-neovim/vscode-neovim/assets/368399/bda569b8-01b2-47ac-85be-b166ea345621)

`a` - add

![image](https://github.com/vscode-neovim/vscode-neovim/assets/368399/83ded824-c2b7-4d31-8d29-bb914e3948a4)

(text object pending)

`iw` - inner word

![image](https://github.com/vscode-neovim/vscode-neovim/assets/368399/f390b01c-b2bc-4ef7-bae9-76abd5bcb66f)

(and finish with the surround you want - this help text actually shows up in the status bar in VSCode as well)

**Closed** 2024-04-29 13:36 UTC
Labels: enhancement, help wanted, good first issue, manager: typing
