### ISSUE TITLE
Forward search `/` sometimes drops characters

### ISSUE THREAD

**Issue by milesfrain** [vscode-neovim/vscode-neovim#683] opened 2021-06-26 18:28 UTC
Characters are sometimes dropped when typing quickly for forward search (and reverse search). In the below video, I'm typing `string`, but only `sring` makes it (the `t` is dropped).

https://user-images.githubusercontent.com/3578681/123522110-1dd34b80-d670-11eb-8b21-15061f424583.mp4

I'm running with an empty `~/.config/nvim/init.vim` for this test case.

Version info:
- vscode `1.57.1`
- vscode nvim extension: `0.0.82`
- nvim: `v0.5.0-dev+1372-g056c464e8`

**Comment by angshumanHalder** [comment] 2021-06-26 20:28
I am having the same issue but I am facing it with "w". 

Version info:

vscode: 1.57.1
vscode nvim extension: 0.0.82
nvim:  v0.5.0-dev+24e0c16fd

**Comment by tlc** [comment] 2021-07-02 16:05
I'm seeing this as well.  I really have to slow my typing to get all chars recognized.

**Comment by poleprogger** [comment] 2021-08-04 21:07
Same here

vscode 1.58.0
vscode nvim extension: 0.0.82
nvim v0.5.0

> I am having the same issue but I am facing it with "w".
> 
> Version info:
> 
> vscode: 1.57.1
> vscode nvim extension: 0.0.82
> nvim: v0.5.0-dev+24e0c16fd

**Comment by poleprogger** [comment] 2021-08-05 15:57
I did some digging and found out that the issue happens in the file command_line_managers.ts. There is a method onCmdChange and here

`     private onCmdChange = async (e: string, complete: boolean): Promise<void> => {
        let keys = "<C-u>" + normalizeInputString(e);
        if (complete) {
            keys += "<C-e>";
        }

       await this.client.input(keys);
`

The last line calls the NeovimClient which then triggers another change in the input field and removes the character w and also the character c. Could be that this is not an issue of this extension but on the library it builds on....

**Comment by poleprogger** [comment] 2021-08-06 10:42
> I am having the same issue but I am facing it with "w".
> 
> Version info:
> 
> vscode: 1.57.1
> vscode nvim extension: 0.0.82
> nvim: v0.5.0-dev+24e0c16fd

I found what is causing the issue with dropping w and c characters @angshumanHalder . I removed the cmap mapping in my **init.vim** and this solved the issue for me.

**Comment by samsonmking** [comment] 2021-09-10 21:41
I was able to resolve this problem by setting the following in my `init.vim`:
```
set notimeout ttimeout ttimeoutlen=10
```

I previously had `ttimeoutlen` set to a higher value, causing neovim to wait awhile for each keycode to timeout.

**Comment by Doomwhite** [comment] 2021-11-22 13:13
> 

This made the search even for to me, now it's constantly updating it self.

**Comment by Doomwhite** [comment] 2021-11-22 13:13
> I was able to resolve this problem by setting the following in my `init.vim`:
> 
> ```
> set notimeout ttimeout ttimeoutlen=10
> ```
> 
> I previously had `ttimeoutlen` set to a higher value, causing neovim to wait awhile for each keycode to timeout.

This made the search even for to me, now it's constantly updating it self.

**Comment by Christopher-Bradshaw** [comment] 2021-12-27 09:02
I've got the same problem and from some debugging the issue is with this line

https://github.com/asvetliakov/vscode-neovim/blob/e87f0fc5441dc0688e1ea545fb41f8290bbe31b3/src/command_line.ts#L78

Commenting that out fixes this problem, but then (as the comment above it suggests) you can't use things like ctrl-l when doing searches. 

I haven't quite got to the bottom of this, but I'm pretty sure there is a race condition where if you type fast, before the change for the first char is fully processed, the second is started. We then enter a period of duelling updates as the `input.value` switches back and forth and the `onChange` handler keeps firing until finally resolving one way or another. I'll keep looking because this is a real annoyance for me, but I don't write much JS so might not get anywhere...

**Comment by Christopher-Bradshaw** [comment] 2021-12-28 06:32
From a bit more debugging, I'm reasonably confident that this is what is happening. I'd be happy if someone else anyone else can verify/sanity check this though :)

* When we type, it immediately sets the input.value (in the CommandLineController quickpick).
* Typing also triggers the onchange event in CommandLineController which triggers the OnCmdChange in CommandLineManager
* Which triggers a neovim notification which triggers a redraw with a cmdline_show event (and the current text that we just typed)
* Which updates `this.input.value` here https://github.com/asvetliakov/vscode-neovim/blob/e87f0fc5441dc0688e1ea545fb41f8290bbe31b3/src/command_line.ts#L78
* In the default case of typing normal chars, this should be a no-op (as the input.value was already set by our typing) and so the onChange handler does not get triggered again and all is well.

But

If we type a second letter before this flow gets to that update, our typing has modified `input.value` (v2). This change is overwritten back to v1 and because this involves a change, the onchange handler is again called (with v1)! Once our second change gets to that point, it is also no longer a no-op and the onchange handler is again called (v2)! And this goes around and around until it somehow breaks out of the cycle (I'm still not 100% sure how).

So what to do?

* We can't remove the update in step 3 as things like `C-l` (which do not update `input.value` directly and only do it through the neovim notification would then not work). 
* But I can't see an easy way to ensure that one change has fully propagated before a second starts (maybe with some kind of lock?)

Unless I have a good idea, I'll probably stop looking at this now. I'll probably also just run a version of this extension with that second update commented out. I didn't know about `C-l` before this and while it is pretty cool, the issues in the common case of just typing are far more annoying to me.

**Comment by jgrau** [comment] 2022-02-08 22:42
> > I am having the same issue but I am facing it with "w".
> > Version info:
> > vscode: 1.57.1
> > vscode nvim extension: 0.0.82
> > nvim: v0.5.0-dev+24e0c16fd
> 
> I found what is causing the issue with dropping w and c characters @angshumanHalder . I removed the cmap mapping in my **init.vim** and this solved the issue for me.

This comment resolved the issue for me. I had the following line in my init.vim

```
cmap w!! w !sudo tee %
```

Removing that line made `w` work again.

**Comment by vlrevolution** [comment] 2022-04-02 21:19
> `/dist/extension.js` for `this.mode||(this.input.value=e)` and delete everything including and after the `||`. Actually ``

Thank you, you are the best! The fix you recommended is godsent!

**Comment by jweickm** [comment] 2022-04-04 10:07
> Edit: If you want to do this, search the compiled `.vscode/extensions/asvetliakov.vscode-neovim-0.0.83/dist/extension.js` for `this.mode||(this.input.value=e)` and delete everything including and after the `||`. Actually `ctrl-l` still kinda works, it just doesn't show up in the search box.

This worked really well for me. I had even been considering to go back to the Vim emulation extension because this issue had been bugging me. Props to @Christopher-Bradshaw for finding such a well-hidden issue + solution!

As it wasn't immediately clear to me what I had to do, I'll write down the steps again for others to follow:

- Go to the vscode extensions folder
  - Windows `%USERPROFILE%\.vscode\extensions`
  - macOS `~/.vscode/extensions`
  - Linux `~/.vscode/extensions`
- From there open `asvetliakov.vscode-neovim-0.0.83/dist/extension.js`
- Make a backup of `extension.js`
- Search for `this.mode||(this.input.value=e)` (there should only be one search result)
- Leave(!) `this.model` and delete only this part: `||(this.input.value=e)`
- Safe and you should be good to go

**Comment by harrisonmg** [comment] 2022-04-07 21:17
@Christopher-Bradshaw Great work! This is kind of a tough issue. Without any insight into when a `<c-l>` send takes place, we can't know when a `cmdline_show` event will show up and clobber input.

A code comment also refers to "`<c-w><c-r>`", but from what I can tell `<c-w>` is handled manually and `<c-r>` just doesn't really work (the character entered after `<c-r>` doesn't go straight to nvim, it goes through `onCmdChange` and `<c-u>` gets prepended to it before getting sent to nvim).

Based on this, it seems the best option would be to make new commands for `<c-l>` and `<c-r>` that go through the `CommandLineController` so that we can queue up further inputs while waiting for the expected `cmdline_show` event (and also handle inputs after `<c-r>` correctly). This seems like kind of a fragile solution based on my limited knowledge of edge cases.

Does anybody have thoughts about adding a VSCode setting to simple toggle the change @Christopher-Bradshaw details? That way we can easily preserve what functionality currently exists while providing an out of the box method for others to deal with the bug?

**Closed** 2022-06-30 18:34 UTC
