### ISSUE TITLE
language-specific hints interfere with editing

### ISSUE THREAD

**Issue by RaduBerinde** [vscode-neovim/vscode-neovim#946] opened 2022-06-28 20:31 UTC
I'm using vscode-neovim with rust-analyzer. The issue I'm having is that the type/field/argument hints make editing very confusing.

For example:
![image](https://user-images.githubusercontent.com/16544120/176278430-67286200-8ce3-4c5a-b587-1af630c3c0cd.png)

If I want to edit the mass, I can't place the cursor under the `5`. It is either under the `m` or under `.`. This always interrupts the "flow" of editing and feels janky.

I believe many other languages have these types of hints so I don't think it's a rust specific issue.

Ideally, the cursor would never be under one of these hints. In lieu of that, it would be useful if there was a way to make the hints just disappear on the line that the cursor is on.

**Comment by theol0403** [comment] 2022-06-29 16:33
Can you check if this also happens with vscodevim? This is likely something that can't really be fixed with this plugin, I think it might be up to vscode to decide where to render the "first" character of the word (before or after hint).

**Comment by grddavies** [comment] 2022-12-14 12:19
I can confirm that this also happens using vscodevim.

There is an issue discussing how to improve the inlay hints implementation in the vscode repo https://github.com/microsoft/vscode/issues/127703

I found that setting `"editor.inlayHints.enabled": "offUnlessPressed"` helps my editing workflow, as inlay hints are only shown when holding `ctrl+alt` or `ctrl+option`

**Closed** 2022-12-30 01:23 UTC
Labels: wontfix, upstream

**Comment by rbits0** [comment] 2024-05-24 08:24
https://github.com/microsoft/vscode/issues/127703 hasn't been updated in a while. That issue is referring to a different problem though. With vscode-neovim, when the cursor is supposed to be on the first character after the hint, it is instead on the first character of the hint. 
![image](https://github.com/vscode-neovim/vscode-neovim/assets/56014573/edce7d3b-3919-4338-ba63-8b7d1f0d0609)
vscode-neovim should put the cursor right after the hint whenever it currently displays it in the hint.

This is an important problem for me, because right now, it makes it look like the cursor is before the character, when it is actually on it. It's hard to figure out what character I'm editing.

**Comment by theol0403** [comment] 2024-05-24 22:42
We correctly tell vscode where to put the cursor. The inlay hint is out of our control. See if this happens with vscodevim. If yes, then vscode devs must fix.
