### ISSUE TITLE
Undo and Redo is not consistent

### ISSUE THREAD

**Issue by tyctor** [vscode-neovim/vscode-neovim#1139] opened 2023-01-26 10:39 UTC
### Describe the bug

when i do undo with many steps and after i do redo to last version i dont get same code

somewhere is added line, somewhere is added character...

### Steps to reproduce

- open file 
- do lot of changes (pres `u` for about 10 seconds and do redo back)
- undo to start
- redo to end

version will be not same

### Expected behavior

same version after all undo and redo steps

**Comment by justinmk** [comment] 2023-01-26 10:54
do the "lot of changes" involve insert-mode edits? does it happen if you only do normal-mode edits (don't enter insert-mode)

**Comment by tyctor** [comment] 2023-01-26 10:59
> do the "lot of changes" involve insert-mode edits? does it happen if you only do normal-mode edits (don't enter insert-mode)

yes, i do `i`, 'I' or `a` when i want to insert new text

**Comment by BlackLight** [comment] 2023-02-01 21:14
This is a bug that has been occurring for a while to me.

It looks like neovim's and VSCode's undo/redo stacks are managed independently and can easily get out of sync (there are also several issues being opened about it).

My workaround has been to explicitly add mappings for `u` and `<C-r>` to my neovim configuration if it detects that it's running in VSCode, so it'll be forced to use VSCode's undo stack:

```vim
if exists('g:vscode')
    " Keep undo/redo lists in sync with VSCode
    nmap <silent> u <Cmd>call VSCodeNotify('undo')<CR>
    nmap <silent> <C-r> <Cmd>call VSCodeNotify('redo')<CR>
endif
```

**Comment by juliannoble** [comment] 2023-02-21 16:05
I've noticed that on undo to last change, the file is the same - but still flagged as dirty by vscode.

The OP stated: "somewhere is added line, somewhere is added character..."  
Perhaps the OP could post back here after verifying with a small file if there is actually a difference or if they are just noticing the fact that the vscode tab shows it as changed, and prompts to save the 'changes you made' even though there are none.

I see VSCodeVim had a similar issue a while back: https://github.com/VSCodeVim/Vim/issues/3201

**Comment by morew4rd** [comment] 2023-04-13 18:36
@BlackLight thanks! My issue was making a change and undoing wasn't resetting the "unsaved" status of the file. Prevented me from enjoying this extension.

Here's the `lua` version:

```lua
if vim.g.vscode then
    -- undo/REDO via vscode
    vim.keymap.set("n","u","<Cmd>call VSCodeNotify('undo')<CR>")
    vim.keymap.set("n","<C-r>","<Cmd>call VSCodeNotify('redo')<CR>") 
end

```

**Comment by theol0403** [comment] 2023-07-05 06:59
* the OP's bug is general buffer desync and unfortunately is difficult to troubleshoot
* the remaining discussion about dirty file is duplicate of https://github.com/vscode-neovim/vscode-neovim/issues/247

**Closed by theol0403** 2023-07-05 06:59 UTC

**Comment by dgokcin** [comment] 2024-08-05 07:52
@blacklight @morew4rd 

you guys made my day. you wont believe how long I have been ignoring this. I tried different vscode remaps etc. but this was the solution!
