### ISSUE TITLE
Rendering issues after many cycles of shift + v selecting, going into insert mode, going into visual mode

### ISSUE THREAD

**Issue by Andrew-Pynch** [vscode-neovim/vscode-neovim#1004] opened 2022-08-12 22:13 UTC
Greetings,

I have been getting a graphic but (often) lately wherein after doing common actions such as
- selecting a code block with shift + v
- going into visual mode 
- going into insert mode 

I will produce strange artifacts as depicted in this screenshot. Additionally, some blocks will remain highlighted even if I have escaped them. 

Not sure if this is expected behavior or if there are work arounds. Please inform if this is just PEBKAC

![image](https://user-images.githubusercontent.com/43330642/184451367-d1bd0b21-1548-4bd7-8c51-5c28877f3372.png)

**Comment by Andrew-Pynch** [comment] 2022-08-12 22:14
I noticed that the weird highlight errors primarily get triggered specifically by going into insert mode via the use of "o" while in visual mode

**Comment by Andrew-Pynch** [comment] 2022-08-12 23:33
Created this short gif

Repro steps 
> start in visual mode
> press o
> code / move around normally, select some text with the cursor

NOTE: Pressing escape or going back into insert mode will not unselect this text, it remains selected until I close the file

https://gyazo.com/488152507451913a348dd482f3ce9e84

Output of code -version
```sh
code -version
Warning: 'e' is not in the list of known options, but still passed to Electron/Chromium.
Warning: 'i' is not in the list of known options, but still passed to Electron/Chromium.
Warning: 'o' is not in the list of known options, but still passed to Electron/Chromium.
1.70.0
da76f93349a72022ca4670c1b84860304616aaa2
x64
```
nvim for vscode version 
```sh
v0.0.89
```

**Comment by Andrew-Pynch** [comment] 2022-08-12 23:40
Sollution: I downgraded my installation to version 
```sh
v0.0.85
```

and can no longer reproduce!

**Comment by theol0403** [comment] 2022-08-15 16:20
I think this is caused by extmark support. No workarounds, and not sure how to fix.

**Comment by theol0403** [comment] 2022-08-15 16:21
Do you map a custom use of `o` in visual mode? For me, it moves the anchor to the other end of the selection.

**Comment by Andrew-Pynch** [comment] 2022-08-15 16:40
Nope no custom mappings. Just the default configuration. Would it be helpful if I exported my keybindings for you though?

I guess if there aren't any work arounds we can just close this issue for now. I will continue using 0.0.85.

**Comment by theol0403** [comment] 2023-10-05 12:57
Might be fixed by https://github.com/vscode-neovim/vscode-neovim/pull/1449, let me know if not.

**Closed by theol0403** 2023-10-05 12:57 UTC
Labels: category: visual, manager: highlight
