### ISSUE TITLE
The status bar at the bottom does not change from "--INSERT--" to normal if use "jj" as <ESC> to switch mode

### ISSUE THREAD

**Issue by milanglacier** [vscode-neovim/vscode-neovim#810] opened 2022-01-26 05:16 UTC
Dear developer:

Hi!

I'm using vscode 1.63.2(universal) on Mac. My  vscode-neovim version is 0.6.1 (arm native), my vscode-neovim version is 0.0.83. 

Following README.md, when try to use "JJ" for <ESC>, to change from switch mode to normal mode, the statusbar at the bottom still remains "--INSERT--". (But "JJ" can switch the mode successfully). While on the contrary, when use `<C-C>`, `<ESC>`, `<C-[>` to switch mode, I found that the "--INSERT" vanishes!

Below is two screenshot as contrast:

The first screenshot shows that, while in normal mode (you can see the cursor is a square. If it is in insert mode, the cursor should be a verticle bar "|"), but the status bar shows a "--INSERT", which is resulted by using "JJ" to switch from insert mode to normal.
<img width="563" alt="Screen Shot 2022-01-26 at 12 06 04 AM" src="https://user-images.githubusercontent.com/45728125/151107097-7d3f7113-995a-49fc-901a-7b1afb22fd02.png">

The second screenshot shows that, while in normal mode, the status bar won't show a  "--INSERT--".
<img width="572" alt="Screen Shot 2022-01-26 at 12 12 37 AM" src="https://user-images.githubusercontent.com/45728125/151107568-93e93ca9-5be9-4707-a756-2c5372772eaf.png">

Thanks for your hard time working on this great project, I really appreciate for the convenience this great project brings me.

**update**:

I find that this behavior doesn't only happen only for "jj". `ESC`, `C-C`, `C-[` will also encounter the issue that 
the "--insert--" cannot vanish as long as you type something in insert mode and switch to normal mode. However, if you do not type anything in insert mode and `ESC` / `C-c` / `C-[` to switch to normal mode, the "--insert--" will vanish.

**Comment by theol0403** [comment] 2022-01-26 17:10
Thank you for the great bug report, but this is a duplicate of #270 and is fixed by #772.

**Closed by theol0403** 2022-01-26 17:10 UTC

**Comment by milanglacier** [comment] 2022-01-26 20:29
> Thank you for the great bug report, but this is a duplicate of #270 and is fixed by #772.

I don’t see the extension update in vscode marketplace. The latest version is still at December 21. Should I manually download the github repo and update it?

**Comment by theol0403** [comment] 2022-01-26 20:32
For now you must build the extension yourself. Hopefully I can find time to figure out how to make a release soon (I just got the ability to make releases on this repo).
Use `vsce package` to make a vsix

**Comment by asvetliakov** [comment] 2022-01-26 20:35
Hey @theol0403 hit me by email to devpieron@gmail.com and i'll share vsce token
