### ISSUE TITLE
VIM Command Line ctrl+p only returns last command and ctrl+n doesn't work at all

### ISSUE THREAD

**Issue by vlrevolution** [vscode-neovim/vscode-neovim#689] opened 2021-07-02 21:50 UTC
What could be causing this?

**Comment by theol0403** [comment] 2021-07-03 19:59
Humm, I am also experiencing this with the latest neovim. I feel like the problem is relatively recent?

**Comment by vlrevolution** [comment] 2021-07-03 20:09
Yes, I tried with empty neovim config and still get the same, also with most VSCode plugins disabled. I am thinking recent VSCode updates have broken something about cmdline. Anyone else experience this?

**Comment by mizagog** [comment] 2021-07-05 18:13
i've had it for a while (even before NVIM 5), but i didn't have a go with an empty config, also i'm on Windows.

**Comment by vlrevolution** [comment] 2021-07-05 18:48
Yeah, I am also on windows.

**Comment by sisrfeng** [comment] 2021-07-23 04:40
+1

**Comment by theol0403** [comment] 2022-06-30 18:34
Fixed by #908

**Closed by theol0403** 2022-06-30 18:34 UTC
