### ISSUE TITLE
Delay on jj for ESC

### ISSUE THREAD

**Issue by touhidulShawan** [vscode-neovim/vscode-neovim#590] opened 2021-03-27 16:31 UTC
When I type jj to ESC sometimes it does not go to normal mode immediately. One j character remains on the editor. What should I do?

**Comment by samvv** [comment] 2021-03-30 11:06
I'm not sure I fully understand the issue you're having. Did you type `jj<Esc>`? If so, it might be you accidentally typed `j<Esc>j`, in which case it is normal that there remains one `j` in the editor. Have you tried the same key combo a bit slower to make sure you did not have a typo?

If this still is an issue, have your tried the same combo with an empty `init.vim`? Plugins sometimes interact in complex ways, and may trigger such a bug.

**Comment by samvv** [comment] 2021-03-30 11:46
Oh OK sorry my bad I missed the relevant part in the README documenting this feature. Will try to reproduce after I'm done with another bug.

**Comment by theol0403** [comment] 2022-04-29 03:36
Duplicate of #330

**Closed by theol0403** 2022-04-29 03:36 UTC

**Comment by seriiserii825** [comment] 2023-04-14 06:56
Why this question is closed, where is the right answer? 
How to add delay?
