### ISSUE TITLE
Centering editor when using Find Next

### ISSUE THREAD

**Issue by C-Rmoser** [vscode-neovim/vscode-neovim#767] opened 2021-11-05 11:24 UTC
I'm using these 2 lines in my init.vim to keep my editor centered when going through search results.
nmap n nzz
nmap N Nzz

E.g. /app<CR> to start a search for "app" in my current file and then "n" to jump to the next result.
In neovim that works perfectly fine. In VsCode however it does only work for all lowercase search results "app". When I'm jumping to an "App" search result, it just gets ignored. Searching for uppercase results explicitly with /App also does not work.

Why does that happen? Is there a work around? 

Edit: I also use these:
set ignorecase
set smartcase

**Comment by pauloalves86** [comment] 2021-12-14 12:20
I have a problem that might be connected.

I `/word` and the editor goes to the first occurrence found. Case does not matter. There is only one in the visible area, but there is another one somewhere else. I hit `n` and nothing happens, but then I move my cursor with `j`, for example, and now the previous command `n` resolves.
The command `n` works on all occurrences inside the visible area, nonetheless, it fails to update the buffer on the first occurrence outside the visible area.

Having two occurrences not visible in the same buffer are enough to reproduce the issue.

**Comment by theol0403** [comment] 2022-04-30 03:42
Seems to work for me

**Comment by theol0403** [comment] 2022-04-30 03:42
@pauloalves86 I think there is duplicate of that somewhere

**Closed by theol0403** 2022-04-30 03:42 UTC
