### ISSUE TITLE
Find and replacement is not real-time rendering like neovim

### ISSUE THREAD

**Issue by MiracleUNS** [vscode-neovim/vscode-neovim#1006] opened 2022-08-13 23:19 UTC
find and replacement in vscode-neovim: 
![image](https://user-images.githubusercontent.com/88761745/184516365-3c923a53-ffb0-475a-9a18-f787668124a6.png)

find and replacement in neovim
![image](https://user-images.githubusercontent.com/88761745/184516379-098db6e6-c8d8-4f7d-8eab-b2e2f80f6c8f.png)

As can be seen, in neovim the find and replacement result is rendering in real time, but not in vscode-neovim.

**Comment by theol0403** [comment] 2022-08-15 16:16
Duplicate of https://github.com/vscode-neovim/vscode-neovim/issues/329

**Closed by theol0403** 2022-08-15 16:16 UTC
