### ISSUE TITLE
Korean input error(가나다 --> 간낟다)

### ISSUE THREAD

**Issue by edicon** [vscode-neovim/vscode-neovim#1005] opened 2022-08-13 13:26 UTC
Error when entering consonants and vowels to write Hangul.
가나다(input) space or enter key --> 간낟다 (error), The consonants of the last letter are automatically entered.
If only neovim is used, it is entered normally.

* nvim --version
  NVIM v0.7.2
  Build type: Release
  LuaJIT 2.1.0-beta3
  Compiled by brew@Monterey
  
  Features: +acl +iconv +tui
  See ":help feature-compile"
  
  system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.7.2_1/share/nvim"

* vs code version
  Version: 1.70.1
  Commit: 6d9b74a70ca9c7733b29f0456fd8195364076dda
  Date: 2022-08-10T06:09:06.916Z (3 days ago)
  Electron: 18.3.5
  Chromium: 100.0.4896.160
  Node.js: 16.13.2
  V8: 10.0.139.17-electron.0
  OS: Darwin x64 21.6.0

**Comment by nix6839** [comment] 2022-08-14 02:47
Duplicate issue with https://github.com/vscode-neovim/vscode-neovim/issues/984.
You can downgrade to a version less than `0.0.89` or wait for the release.

**Comment by theol0403** [comment] 2022-08-15 16:13
Duplicate of https://github.com/vscode-neovim/vscode-neovim/issues/984.

**Closed by theol0403** 2022-08-15 16:13 UTC
