### ISSUE TITLE
Map escape to jk without mapping to jj

### ISSUE THREAD

**Issue by pianocomposer321** [vscode-neovim/vscode-neovim#166] opened 2020-02-05 02:50 UTC
Is there a way to map escape to jk without first mapping jj? I understand that it's not the end of the world, but it seems odd to have to first impliment a mapping that I will never use.

**Comment by asvetliakov** [comment] 2020-02-05 23:32
Currently not possible, but can be supported

**Comment by theol0403** [comment] 2022-04-28 00:45
Duplicate of #563.

**Closed by theol0403** 2022-04-28 00:45 UTC
Labels: enhancement, help wanted, good first issue
