### ISSUE TITLE
"module vim.version not found" when $VIMRUNTIME directory is not readable by VS Code

### ISSUE THREAD

**Issue by mbhutton** [vscode-neovim/vscode-neovim#1815] opened 2024-02-18 00:56 UTC
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

NVIM v0.9.5, or 0.10.0, from Github CI release builds 

### Operating system/version

macOS 14.3.1

### Note to maintainers 

_I'm raising this issue mainly as a warning to others, with a suggested workaround (to build Neovim from source).
I'm expecting it to be closed as not worth fixing.
If valid (rather than a misconfiguration), it may be worth adding a note to the README to avoid using the CI builds._

### Describe the bug

The plugin fails with multiple errors (as below) when setting `vscode-neovim.neovimExecutablePaths.darwin` to an `nvim` executable from [the Neovim Github releases page](https://github.com/neovim/neovim/releases), both for current stable releases (0.9.5) and nightly (0.10.0).

It works fine for:
* The homebrew installed `nvim`
* Locally built `nvim`, build on the local machine from source

The output shown in the VS Code `output` pane when loading with a Github CI build of Neovim:
```
2024-02-18 13:31:13.057 [info] 
Error detected while processing pre-vimrc command line..script /Users/matt/.vscode/extensions/asvetliakov.vscode-neovim-1.6.1/vim/vscode-neovim.vim:
line   26:
E5108: Error executing lua vim/_init_packages.lua:0: module 'vim.version' not found:
	no field package.preload['vim.version']
	no file './vim/version.lua'
	no file '/Users/runner/work/neovim/neovim/.deps/usr/share/luajit-2.1/vim/version.lua'
	no file '/usr/local/share/lua/5.1/vim/version.lua'
	no file '/usr/local/share/lua/5.1/vim/version/init.lua'
	no file '/Users/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/vim/version.lua'
	no file '/Users/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/vim/version/init.lua'
	no file './vim/version.so'
	no file '/usr/local/lib/lua/5.1/vim/version.so'
	no file '/Users/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/vim/version.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './vim.so'
	no file '/usr/local/lib/lua/5.1/vim.so'
	no file '/Users/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/vim.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'require'
	vim/_init_packages.lua: in function '__index'
	[string ":lua"]:3: in main chunk
2024-02-18 13:31:13.058 [info]
```

Note the `/Users/runner/work` paths, being paths from the CI runners rather than paths from my local machine. 

All debug attempts to find a faulty `$VIM` or `$VIMRUNTIME` or `runtimepath` have come up short, as they've all shown the expected and correct `share/nvim/runtime` path relative to the `nvim` executable. And these `nvim` executables can all be run from the terminal without issue. 

### Steps To Reproduce

1. Go to https://github.com/neovim/neovim/releases
2. Download the latest nvim-macos.tar.gz (0.9.5 or 0.10.0, result is identical)
3. Run `xattr -c ./nvim-macos.tar.gz`
4. Run `tar xzvf nvim-macos.tar.gz`
5. Run `./nvim-macos/bin/nvim`, to test the executable 
6. In VS Code `settings.json`, set `"vscode-neovim.neovimExecutablePaths.darwin": "/path/to/nvim-macos/bin/nvim"`
7. Restart VS Code 
8. VS Code shows multiple errors as above, both on startup, and then frequently, during edits.

### Expected Behavior

The plugin should load without errors and function normally during edits.

### Suggested workaround

Either using a Neovim build from a package manager (e.g. homebrew), or built locally from source, and avoid using the Github CI release builds of Neovim with this plugin.

**Comment by justinmk** [comment] 2024-02-18 14:54
> module 'vim.version' not found:

That exists on 0.10. You must have misconfigured the path to `nvim`. Try `:version` command from vscode, what does it report?

**Comment by justinmk** [comment] 2024-02-18 14:56
It also exists on Nvim 0.9

This likely happening because you have not installed the Nvim runtime files and you haven't set `$VIMRUNTIME` correctly.

I suppose vscode-neovim could try to automatically set `$VIMRUNTIME` if it sees that `bin/nvim` lives next to a `runtime/` directory.

**Comment by mbhutton** [comment] 2024-02-18 22:50
After more trial and error, it turned out that the root cause was a permissions issue for the `Downloads` directory.

By default VS Code on macOS doesn't have permission to read from the `$HOME/Downloads` directory, and this is simply how it fails when trying to use an `nvim` executable from a directory that VS Code doesn't have permission to read. Oddly it's able to spawn the `nvim` executable itself, but just without the ability to read its own runtime files.

So, clearly no bug in the plugin, so I'll close this issue. I'll update the title to indicate the root cause in case anyone else stumbled on this. 

Thanks!

**Comment by justinmk** [comment] 2024-02-18 22:55
Thank you for debugging that!

I think `nvim` should probably detect this and show a more useful error, since it is tricky to troubleshoot.

Let's keep this issue open, though ideally it will be resolved in Nvim itself.

**Comment by justinmk** [comment] 2024-02-18 23:12
> these `nvim` executables can all be run from the terminal without issue.

Thanks to your troubleshooting, I confirmed the issue _is_ reproducible in the terminal if you remove "Downloads" access permissions for the terminal app:

<img width="457" alt="image" src="https://github.com/vscode-neovim/vscode-neovim/assets/1359421/a9f13422-27ad-4129-90f3-6792407f0083">

And `!ls $VIMRUNTIME` is a way to test for the problem:

```
:!ls $VIMRUNTIME
ls: /Users/xx/Downloads/t/nvim-macos/share/nvim/runtime: Operation not permitted
shell returned 1
```

**Comment by justinmk** [comment] 2024-02-18 23:50
Created https://github.com/neovim/neovim/issues/27527 

Nvim's `:checkhealth` command already warns about this case, but it's worth checking if the Lua loader error could be improved.

# Proposal

vscode-neovim itself can and should check if `$VIMRUNTIME` is accessible.

**Closed** 2024-02-19 20:47 UTC
Labels: enhancement, category: startup, category: logging
