### ISSUE TITLE
ESC out of Add Cursor Below mode breaks when neovim extension is installed

### ISSUE THREAD

**Issue by abulka** [vscode-neovim/vscode-neovim#1178] opened 2023-03-17 09:41 UTC
The ability to `ESC` out of `Add Cursor Below` mode breaks when neovim extension is installed. 

In normal vscode I can `editor.action.insertCursorBelow` repeatedly to extend my cursor, then ESC out of it to get back my single cursor.  When neovim extension is installed, the ESC key does nothing and I am stuck with my multiple cursors.

P.S. My shortcut on my Mac for extensing the cursor is
```json
{
  "key": "alt+cmd+down",
  "command": "editor.action.insertCursorBelow",
  "when": "editorTextFocus"
}
```

Perhaps there is a way out of it using some new mapping, but I can't find any documentation.

**Comment by justinmk** [comment] 2023-03-17 10:53
is this a duplicate of https://github.com/vscode-neovim/vscode-neovim/issues/97 ?

**Comment by abulka** [comment] 2023-03-17 11:18
I don't think so. This is about native vscode functionality being broken by the installation of the neovim extension, not about a proposed multiple cursors feature within neovim mode.

**Comment by justinmk** [comment] 2023-03-17 11:45
https://github.com/vscode-neovim/vscode-neovim/issues/97 is about making vscode-neovim work with vscode's multiple cursors. So I don't see how it's different.

**Closed** 2023-07-05 02:54 UTC
