### ISSUE TITLE
`Ctrl+N` and `Ctrl+P` are not working for the "VIM Command Line"

### ISSUE THREAD

**Issue by wenfangdu** [vscode-neovim/vscode-neovim#853] opened 2022-04-06 11:17 UTC
`Ctrl+N` and `Ctrl+P` work for the `workbench.action.quickOpen` file picker, but do not work for the "VIM Command Line"

![image](https://user-images.githubusercontent.com/28700378/161962613-421d22e7-b12f-4cb4-b53d-6dea0f78f27e.png)

![image](https://user-images.githubusercontent.com/28700378/161963064-c32dba4a-e98a-4393-8539-07e6dfe265fb.png)

**Comment by wenfangdu** [comment] 2022-04-06 11:29
Removing these two bindings will work:

![image](https://user-images.githubusercontent.com/28700378/161964920-b67a4874-64c9-45fa-9f35-eda69841fe92.png)

**Comment by theol0403** [comment] 2022-04-27 21:37
Duplicate of #708

**Comment by wenfangdu** [comment] 2022-04-30 10:05
@theol0403 Not a duplicate of #708, this issue is to disable the command history navigation when using Ctrl + N/P.

**Comment by theol0403** [comment] 2022-06-30 18:37
To disable command history navigation (now fixed), delete those two keybindings.

**Closed by theol0403** 2022-06-30 18:37 UTC
