### ISSUE TITLE
How to pass vscode selection to neovim visual selection without enable "mouse selection starts visual mode"

### ISSUE THREAD

**Issue by MiracleUNS** [vscode-neovim/vscode-neovim#1008] opened 2022-08-15 12:32 UTC
![image](https://user-images.githubusercontent.com/88761745/184635362-09a12729-1cb6-42b9-b0a8-74f05f464bb0.png)
With mouse selection start visual mode enable, the mouse selection behaves abnormally, is there any approach that can pass vscode selection to neovim visual selection without enable "mouse selection starts visual mode" ?

**Comment by theol0403** [comment] 2022-08-15 16:11
No way currently. Duplicate of #553

**Closed by theol0403** 2022-08-15 16:11 UTC
