### ISSUE TITLE
Composite escape key alters typed letter in non EN layout in insert mode

### ISSUE THREAD

**Issue by kurnev** [vscode-neovim/vscode-neovim#389] opened 2020-09-25 09:19 UTC
**Steps to reproduction:**

1. Add `jj` as composite key in `keybindings.json`:

```json
{
    "command": "vscode-neovim.compositeEscape1",
    "key": "j",
    "when": "neovim.mode == insert && editorTextFocus",
    "args": "j"
}
```

2. Enter insert mode

3. Switch to russian layout. 

4. Attempt to enter russian letter `о` (which is placed right on `j` key).

**Expected result:**

`о` inserted

**Actual result:**

`j` inserted

**Env:**

1. VSCode: Version: 1.49.1
2. NVIM v0.5.0-dev
3. OS Fedora 32
4. init.vim: 

```vimrc
call plug#begin('~/.vim/plugged')
Plug 'tpope/vim-surround'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-unimpaired'
Plug 'posva/vim-vue'
call plug#end()

xmap gc  <Plug>VSCodeCommentary
nmap gc  <Plug>VSCodeCommentary
omap gc  <Plug>VSCodeCommentary
nmap gcc <Plug>VSCodeCommentaryLine

nnoremap <C-h> <Cmd>call VSCodeNotify('workbench.action.focusLeftGroup')<CR>
xnoremap <C-h> <Cmd>call VSCodeNotify('workbench.action.focusLeftGroup')<CR>
nnoremap <C-j> <Cmd>call VSCodeNotify('workbench.action.focusBelowGroup')<CR>
xnoremap <C-j> <Cmd>call VSCodeNotify('workbench.action.focusBelowGroup')<CR>
nnoremap <C-k> <Cmd>call VSCodeNotify('workbench.action.focusAboveGroup')<CR>
xnoremap <C-k> <Cmd>call VSCodeNotify('workbench.action.focusAboveGroup')<CR>
nnoremap <C-l> <Cmd>call VSCodeNotify('workbench.action.focusRightGroup')<CR>
xnoremap <C-l> <Cmd>call VSCodeNotify('workbench.action.focusRightGroup')<CR>
```

**Comments**

Adding `keyboard.dispatch": "keyCode` in vscode didn't help.

**Comment by theol0403** [comment] 2022-04-29 00:56
Duplicate of #653

**Closed by theol0403** 2022-04-29 00:56 UTC
Labels: bug
