### ISSUE TITLE
VSCode visual to nvim visual

### ISSUE THREAD

**Issue by tobealive** [vscode-neovim/vscode-neovim#921] opened 2022-05-24 04:09 UTC
Is it possible to do it the other way around as described in the readme (Which shows how to use nvim selection to vscode selection).

E.g, smart-selection produces a VSCode selection and is therefore not usable with the regular vim commands c,d,y etc.

Tried to substitute with wildfire.vim, which unfortunately is not working. NVIM treesitters inbuilt smart select is not available in vscode, obviously.

**Comment by theol0403** [comment] 2022-05-24 15:26
You might be able to get tree-sitter working in nvim if you disable syntax hl. Otherwise, maybe a new implementation of visual selection -> nvim is needed that might fix some issues with the current mouse visual selection code (instead of mouse move -> visual mode it could be vscode selection changed -> visual mode).

**Comment by tobealive** [comment] 2022-05-24 15:53
The implementation solution sounds promising. Are there plans or works in progress for it to be implemented? And is there something we can contribute to this?

**Comment by theol0403** [comment] 2022-05-24 17:27
Unfortunately no plans, there are a lot of possible improvements to this plugin but help is needed for them and they are quite technical. As I don't have much time and lack experience, collaboration is needed. I'm not sure where to start looking, but hopefully visual mode issues can be tackled by someone (myself included) sometime soon.

**Comment by theol0403** [comment] 2022-08-04 19:53
Duplicate of #553

**Closed by theol0403** 2022-08-04 19:53 UTC
