### ISSUE TITLE
bug: cmdline commands through keymaps execute before complete

### ISSUE THREAD

**Issue by danielaird27** [vscode-neovim/vscode-neovim#2028] opened 2024-05-29 14:58 UTC
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

NVIM v0.9.4

### Operating system/version

Windows 11

### Describe the bug

It seems like some cmdline commands setup through keymaps execute too early and end up typing the remainder of the command into the text. I can confirm the issue is present with one keymap in my nvim config:

```
vim.keymap.set('v', '/', 'y/\\V<C-R>=escape(@",\'/\')<CR><CR>')
```

When I highlight a symbol and hit the "/" key, the "cape(@",'/')" of the keymap's command gets entered into the current buffer. It doesn't seem to happen all the time but it happens most of the time.

Highlighting the symbol before hitting the "/" key:
![Screenshot 2024-05-29 104242](https://github.com/vscode-neovim/vscode-neovim/assets/57294055/1d782947-0a45-4f67-9ca9-7a5164339cc7)

After hitting the "/" key:
![Screenshot 2024-05-29 104257](https://github.com/vscode-neovim/vscode-neovim/assets/57294055/6b5f0af4-c196-4cd8-980a-1d18b35c505a)

This problem is present in vscode-neovim 1.13.1 and 1.13.0 but is not present in 1.12.0.

Note: I could not run with vscode-neovim.neovimClean=true to test this because that would remove the keymap. However, the fact that using vscode-neovim 1.12.0 makes this problem go away leads me to believe the problem isn't in my very light config.

### Steps To Reproduce

1. Add ```vim.keymap.set('v', '/', 'y/\\V<C-R>=escape(@",\'/\')<CR><CR>')``` keymap to your nvim config.
2. Open a buffer with and fill it with the Python example given in the description.
3. Highlight funcA and hit the "/" key.

### Expected Behavior

I expect there to be no text entered into my buffer when starting a search with the provided keymap. That is the functionality shown in vscode-neovim 1.12.0.

**Comment by ollien** [comment] 2024-05-29 16:13
Thanks for the report. Indeed, I can confirm this seems to be a regression from #2001. Will investigate further.

**Comment by ollien** [comment] 2024-05-29 20:28
Oof, I did find a fix for this specific issue by just moving this call to `input.show()` to after the if statement. This prevented an erroneous firing of `onChange` when the value was updated; the zero value of `pendingNvimUpdates` cases  `escape` to be inputted to the editor directly, rather than the cmdline.

https://github.com/vscode-neovim/vscode-neovim/blob/09571212c176225ea3eca4f351296ed464b804b5/src/cmdline_manager.ts#L119

However, I think there's a deeper problem here that needs to be investigated. It seems that as of the refactor to move `CmdlineController` into `CmdlineManager`, a race condition has cropped up that prevents `<C-r>=` from working properly at all. Here's a quick set of repro steps

1. Press `/`
2. Press `<C-r>=` and type 'asdf'.
3. Hit enter, and watch the cmdline disappear.

In stock nvim, and in older versions of this plugin, the cmdline would show with `asdf` at that point. Looking at the logs (with a couple of additions of my own), you can see that the `<Esc>` ([here](https://github.com/vscode-neovim/vscode-neovim/blob/09571212c176225ea3eca4f351296ed464b804b5/src/cmdline_manager.ts#L157)) is being sent _after_ the new secondary commandline is shown.

```
2024-05-29T20:22:40.109Z CmdLine: cmdline_show: ignoring cmdline_show because no redraw expected: "'abc"
2024-05-29T20:22:40.109Z CmdLine: cmdline_show: "48,',50,abc"
2024-05-29T20:22:40.109Z CmdLine: cmdline_show: ignoring cmdline_show because no redraw expected: "'abc"
2024-05-29T20:22:40.219Z CmdLine: cmdline_show: "48,',50,abc"
2024-05-29T20:22:40.220Z CmdLine: cmdline_show: ignoring cmdline_show because no redraw expected: "'abc"
2024-05-29T20:22:40.232Z CmdLine: onChange: sending cmdline to nvim: "'abc" + "'" -> "'abc'"
2024-05-29T20:22:40.233Z CmdLine: cmdline_show: "50,',50,abc,50,'"
2024-05-29T20:22:40.233Z CmdLine: cmdline_show: ignoring cmdline_show because no redraw expected: "'abc'"
2024-05-29T20:22:40.233Z CmdLine: cmdline_show: "50,',50,abc,50,'"
2024-05-29T20:22:40.233Z CmdLine: cmdline_show: ignoring cmdline_show because no redraw expected: "'abc'"
2024-05-29T20:22:40.340Z CmdLine: cmdline_show: "50,',50,abc,50,'"
2024-05-29T20:22:40.340Z CmdLine: cmdline_show: ignoring cmdline_show because no redraw expected: "'abc'"
2024-05-29T20:22:40.418Z CmdLine: cmdline_hide
2024-05-29T20:22:40.418Z CmdLine: cmdline_show: "0,abc"
2024-05-29T20:22:40.418Z CmdLine: cmdline_show: ignoring cmdline_show because no redraw expected: "abc"
2024-05-29T20:22:40.421Z CmdLine: cmdline_show: "0,abc"
2024-05-29T20:22:40.421Z CmdLine: cmdline_show: ignoring cmdline_show because no redraw expected: "abc"
2024-05-29T20:22:40.421Z CmdLine: cmdline_show: "0,abc"
2024-05-29T20:22:40.421Z CmdLine: cmdline_show: ignoring cmdline_show because no redraw expected: "abc"
2024-05-29T20:22:40.421Z CmdLine: Sending <Esc> input for hide
2024-05-29T20:22:40.424Z ModeManager: Changing mode to n
2024-05-29T20:22:40.425Z ModeManager: Setting mode context to normal
2024-05-29T20:22:40.426Z CmdLine: cmdline_hide
2024-05-29T20:22:40.426Z CmdLine: onChange: sending cmdline to nvim: "" + "" -> ""
```

My suspicion is that this wasn't an issue before, because we completely reconstructed the `CmdlineController` for each `cmdline_show`, so the call to `input.hide()` as a result of [this block](https://github.com/vscode-neovim/vscode-neovim/blob/5621eb57ac69abbaf5c4ceff4aafae81e0a1c0ea/src/cmdline_manager.ts#L49-L53) operated on an entirely separate piece of state than that produced by the `cmdline_show`. Now that the state is sprinkled within `CmdlineManager`, there is no "separation" between the state of two instances of the input box.



@theol0403 You'd know best about this given your work here, but my only thought here is to revert to the previous paradigm. That said, your changes had a lot of fiddly bits to make everything line up right, so I'm hesitant to make a big change only to reintroduce a bug you fixed. Maybe there's a simpler solution I'm not seeing?

**Comment by theol0403** [comment] 2024-05-30 00:37
`ignoreHideEvent` wasn't actually working (because it got reset before it was used). looking into it

**Closed** 2024-05-30 15:14 UTC
Labels: bug, manager: command_line
