### ISSUE TITLE
VSCodeCallVisual doesn't work for certain command

### ISSUE THREAD

**Issue by introom** [vscode-neovim/vscode-neovim#1078] opened 2022-11-17 07:47 UTC
Specifically, for this mapping
```
noremap <C-l>e <Cmd>call VSCodeCallVisual('jupyter.execSelectionInteractive', 1)<CR><Esc>
```
There is no effect when pressing "jupyter.execSelectionInteractive"

**Comment by introom** [comment] 2022-11-17 07:49
To be exact, when first invoking the key seq <C-l>e, the jupyter window will launch. 
For  further invocation on <C-l>e, nothing happens.

**Comment by Jendker** [comment] 2022-11-17 09:26
You would need to first pass C-l to nvim, it is described in README. But it would be easier to directly create a mapping in VSCode.

**Comment by introom** [comment] 2022-11-17 09:27
> You would need to first pass key sequence to nvim, it is described in README. But it would be easier to directly create a mapping in VSCode.

yes, I've done that.
```
  // python
  // XXX doesn't work
  {
    "key": "ctrl+l e",
    "command": "vscode-neovim.send",
    "when": "editorLangId == 'python' && editorTextFocus",
    "args": "<C-l>e"
  },

```

**Comment by Jendker** [comment] 2022-11-17 09:37
Key combinations are not that straightforward unfortunately. You could try to mimic the configuration for `jk` combination which is currently in the plugin. But why not create a mapping directly in VSCode?

**Comment by introom** [comment] 2022-11-17 09:38
>  But why not create a mapping directly in VSCode?
I use neovim to select. Creating a binding directly vscode cannot retrieve the neovim selections. Is there a way to achieve that?

**Comment by Jendker** [comment] 2022-11-17 09:41
Once again this will not work because you are trying to run VSCode command on something what VSCode cannot retrieve.
Maybe someone else will have an idea on how to send selection to VSCode.

**Comment by Jendker** [comment] 2022-11-17 13:46
I think that is relevant to you @introom https://github.com/vscode-neovim/vscode-neovim/issues/172

**Comment by introom** [comment] 2022-11-17 14:14
@Jendker I can write custom js functions (through https://github.com/BetterThanTomorrow/joyride) to address this.  I'd like to know what's the command/api to know the start and end of the neovim selection?

**Comment by theol0403** [comment] 2022-11-19 17:34
@introom all the code you have provided looks correct. You don't even need the vscode keybinding, C-l is already sent to VSCode. Not sure what the problem is.

@Jendker sorry but all his code looks correct, this is definitely the way to solve the problem. 

>  Maybe someone else will have an idea on how to send selection to VSCode.

This is the purpose of `VSCodeCallVisual`

This seems to be a duplicate of https://github.com/vscode-neovim/vscode-neovim/issues/771, but since that issue is closed, I'll make this one the official tracker. 

Maybe try to use `xnoremap`?

**Comment by theol0403** [comment] 2022-11-19 17:36
> @Jendker I can write custom js functions (through [BetterThanTomorrow/joyride](https://github.com/BetterThanTomorrow/joyride)) to address this. I'd like to know what's the command/api to know the start and end of the neovim selection?

You would need to use the neovim client class to run `getpos('v')` and `getpos('.')`.

**Comment by introom** [comment] 2022-11-20 02:03
> Maybe try to use xnoremap?
Thanks. This one does not help though.

**Comment by sbischl** [comment] 2023-05-07 12:49
Hi, this issue still seems to exists. I ran into the exact same problem when trying to send code to a Jupyter Notebook. The Notebook opens and then nothing happens. Just as described by @introom

It looks like the Problem is in `vscode-neovim.vim`
https://github.com/vscode-neovim/vscode-neovim/blob/f9bcd2555c01ad238d9eca06f1c051c43ee71b15/vim/vscode-neovim.vim#L77-L91

When invoking `'VSCodeCallVisual('jupyter.execSelectionInteractive', 1)'` the, as I understand, additional arguments  `a:000` are an empty list. These additional arguments get then passed further to `VSCodeNotifyRange()` and then to `rpcnotify()`. Inside `rpcnotify()` `a:000` is no longer an empty list `[]` but a list containing an empty list `[[]]`

My suspicion is that the inner empty list gets passed to `jupyter.execSelectionInteractive`, which takes as optional argument the code to run in the cell. This explains why no code is run. When I modify `vscode-neovim.vim` and remove all occurances of `a:000` inside `VSCodeNotifyVisual`, it works as expected and the selection in Visual mode gets run by the Jupyter notebook 😃

**Closed** 2023-07-21 20:54 UTC
Labels: category: visual
