### ISSUE TITLE
'jk' not working correctly

### ISSUE THREAD

**Issue by HwangTaehyun** [vscode-neovim/vscode-neovim#523] opened 2021-01-11 07:52 UTC
Thank you for a great extension. l love vim so much.

Using this extension in vscode, I found a bug when I type 'jk' in insert mode, and next, I type 'j' very fast. Then j is typed before going normal mode. And when some text is deleted when typing 'jk' and next typing j fast.

Why does this happen? Thank you for your effort.

https://user-images.githubusercontent.com/42465090/104157031-a7c68980-542d-11eb-8c71-1562f723ec1f.mp4

**Comment by pojntfx** [comment] 2021-01-12 09:32
Can confirm this (code-server)

**Comment by asvetliakov** [comment] 2021-01-17 01:12
Related #330

**Comment by mdanics** [comment] 2021-06-22 02:16
I'm also facing this. On Mac 11.4

**Comment by theol0403** [comment] 2022-04-28 00:41
Duplicate of #330

**Closed by theol0403** 2022-04-28 00:41 UTC
Labels: bug
