### ISSUE TITLE
easymotion plugin triggers output, covers editor

### ISSUE THREAD

**Issue by unTanana** [vscode-neovim/vscode-neovim#910] opened 2022-05-20 09:28 UTC
Hey, this issue started happening today, probably after an update of either vscode or this extention.

![image](https://user-images.githubusercontent.com/22821635/169498711-1300c15a-2e9c-40ad-9eea-f44a9e9d72be.png)

As can be seen in this image, when I try to use easymotion to jump around, now the output tab gets filled with easymotion output. I have no idea why this happens all of a sudden, or how to turn it off.

Any help is much appreciated, thank you :)

**Comment by alexkatz** [comment] 2022-05-20 19:51
Started happening to me as well once I upgraded to 0.0.85, I think.

**Comment by theol0403** [comment] 2022-05-20 19:53
This is caused by #868
Potential solutions:
- remove easymotion support entirely (hop.nvim/lightspeed now supported)
- silence easymotion output (might be a config)
- add logic to hide output panel (this isn't an issue in nvim, so maybe there is some api behavior like the plugin manually closing the messages or clearing the screen that we need to react to)

@justinmk thoughts?

**Comment by windwp** [comment] 2022-05-21 01:51
you can `set g:EasyMotion_prompt = ""`

**Comment by alexkatz** [comment] 2022-05-21 23:37
I ended up switching to hop.nvim, and it’s working nicely within vscode so far with extremely minimal setup compared to easymotion. 

Thanks for the suggestion, @theol0403.

**Comment by linzhefeng** [comment] 2022-05-22 10:22
me too, and I just go back to previous version..

**Comment by theol0403** [comment] 2022-05-24 15:37
> you don't need to use a fork with new update you can use [easymotion/vim-easymotion](https://github.com/easymotion/vim-easymotion)

Are you sure? I think easymotion still uses text replacement for the labels, which messes up LSP, and doesn't use extmarks.

**Comment by theol0403** [comment] 2022-05-24 15:38
> me too, and I just go back to previous version..

`set g:EasyMotion_prompt = ""`

**Comment by theol0403** [comment] 2022-06-30 00:06
Workaround for easymotion available. Easymotion is no longer supported. Use hop or lightspeed.

**Closed by theol0403** 2022-06-30 00:06 UTC

**Comment by wenfangdu** [comment] 2022-07-04 13:59
@theol0403 Which vim-easymotion replacement do you personally use, hop, lightspeed, leap, or anything even better?

**Comment by theol0403** [comment] 2022-07-04 14:04
> @theol0403 Which vim-easymotion replacement do you personally use, hop, lightspeed, leap, or anything even better?

Lightspeed

**Comment by wenfangdu** [comment] 2022-07-04 14:11
@theol0403 Thanks, what's your opinion on leap? Just saw you commented it out:

https://github.com/theol0403/dotfiles/blob/9653a2a835325be3f58d1e252ad1aba949e73d57/.config/nvim/vimrc/moon/plugins.moon#L33

**Comment by theol0403** [comment] 2022-07-04 14:12
> @theol0403 Thanks, what's your opinion on leap? Just saw you commented it out:
> 
> https://github.com/theol0403/dotfiles/blob/9653a2a835325be3f58d1e252ad1aba949e73d57/.config/nvim/vimrc/moon/plugins.moon#L33

I like it but currently it doesn't work in vscode because the fake cursor hl can't be changed.

**Comment by infinitewhileloop** [comment] 2023-04-29 10:03
> Workaround for easymotion available. Easymotion is no longer supported. Use hop or lightspeed.

EasyMotion is still mentioned on the [front page](https://github.com/vscode-neovim/vscode-neovim) and in the [wiki](https://github.com/vscode-neovim/vscode-neovim/wiki/Plugins). Should this be changed, to avoid confusion?
