### ISSUE TITLE
JSX Indenting issues

### ISSUE THREAD

**Issue by spmacdonald** [vscode-neovim/vscode-neovim#1037] opened 2022-09-16 14:12 UTC
When written JSX inside a JavaScript file I notice that the indent is wrong when I enter insert mode using `o, O, s, ...` etc.

For example:

```
  return (
    <div>
      <div>
        <HTMLSelect
          options={foo}                        # Press o
   |   <-- cursor goes here
        />
      </div>
    </div>
```

If I am in insert mode and press enter the cursor goes to the correct spot.

```
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-005.local

Extension version v0.0.89
```

I have verified this behaviour with an empty `init.vim` and empty `.config/nvim` and `.local/share/nvim` folders.

Any thoughts on what could be causing this?

Thanks for the hard work, I have learned a lot using this extension!

**Comment by theol0403** [comment] 2022-09-28 19:01
Might be a duplicate of #519. If `syntax on` fixes your issue, please close it.

**Comment by spmacdonald** [comment] 2022-10-07 14:34
Just tried `syntax on` but see the same behaviour.

**Comment by theol0403** [comment] 2022-10-12 18:10
@spmacdonald enter in insert mode uses vscode indent logic, but `o` uses nvim indent logic. Can you see if you experience the same behaviour in terminal nvim? If so, that's where the problem lies.

**Comment by spmacdonald** [comment] 2022-10-12 19:27
Ok, confirmed this seems to be what is happening. 

I wonder is it possible to configure the plugin to use vscode indent logic instead of nvim?

**Comment by theol0403** [comment] 2022-10-12 19:31
No, nvim handles all text manipulation, the only reason vscode logic is used in insert mode is that nvim is effectively disabled during insert mode.

The only workable solution would be to map o/O to vscode commands that create a new line above/before the cursor. This works, but then might break neovim dot repeat, and differs from vscode behaviour. I believe there is still code in this project that refers to a time when this workaround existed.

Anyways I think your best bet is to find a nvim plugin/setting that uses the indentation you want.

**Closed by theol0403** 2022-10-12 19:31 UTC
