### ISSUE TITLE
Weird behaviour after pasting a yanked line when selecting "vi{"

### ISSUE THREAD

**Issue by OfirTadmor** [vscode-neovim/vscode-neovim#116] opened 2019-12-21 14:57 UTC
Seems to add an extra "}" when pasting, 

![image](https://user-images.githubusercontent.com/13004405/71309616-ad13f900-2412-11ea-8e85-b19d67e65138.png)

![image](https://user-images.githubusercontent.com/13004405/71309608-99689280-2412-11ea-83e3-eb577a20d3f3.png)

**Comment by asvetliakov** [comment] 2019-12-21 16:38
This is serious and indicates that buffer in neovim side has messed up.  Do you remember steps you've done *before* pasting?

**Comment by OfirTadmor** [comment] 2019-12-21 16:46
this only happens when yanking a link  "yy", any other type of yank seems to work.
I was afraid it was something to do with my extensions in vscode or auto complete settings inside vscode, but after trying to disable most of them this problem stayed.
were you able to recreate this ?

**Comment by asvetliakov** [comment] 2019-12-21 16:50
Just reproduced, looking

**Comment by asvetliakov** [comment] 2019-12-22 01:51
Looks like upstream issue https://github.com/neovim/neovim/issues/11591

**Comment by xiyaowong** [comment] 2024-04-27 16:37
This issue has been fixed in nvim v0.10.0 (not yet released)

**Closed** 2024-05-17 16:08 UTC
Labels: bug, upstream
