### ISSUE TITLE
[BUG] characters are shifted when text is selected

### ISSUE THREAD

**Issue by Worldbug** [vscode-neovim/vscode-neovim#1107] opened 2022-12-18 13:30 UTC
Starting from version v0.0.95 characters are shifted when text is selected
(v0.0.94 has no problems)
when in visual mode
<img width="967" alt="Screenshot 2022-12-18 at 16 27 51" src="https://user-images.githubusercontent.com/28673120/208300995-991360f6-f62e-44d1-8903-a3b449c80a13.png">

when not in visual mode
<img width="923" alt="Screenshot 2022-12-18 at 16 28 17" src="https://user-images.githubusercontent.com/28673120/208301013-d5afaeed-9e68-4929-ac3e-3c759f379905.png">

**Comment by Worldbug** [comment] 2022-12-18 13:31
VSCode version:
Version: 1.74.1
Commit: 1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a
Date: 2022-12-14T10:32:34.075Z (4 days ago)
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 22.1.0
Sandboxed: No

**Comment by wonrax** [comment] 2022-12-19 04:18
Possibly related, I have no idea what's happening

![image](https://user-images.githubusercontent.com/28887874/208345884-d1ba97be-f35a-499e-8ccb-b0dd4306d541.png)

**Comment by windwp** [comment] 2022-12-22 11:12
this PR  https://github.com/vscode-neovim/vscode-neovim/pull/1100 will fix that

**Comment by ilexite** [comment] 2022-12-22 14:14
I'm having the same issue. This issue only occurs when tab indents are used. With space indents, there is no problem.
This suggests that the issue is a mismatch of the cursor position between vscode and neovim. I hope this helps.

**Comment by theol0403** [comment] 2022-12-30 00:22
Fixed by https://github.com/vscode-neovim/vscode-neovim/pull/1099

**Closed by theol0403** 2022-12-30 00:22 UTC
