### ISSUE TITLE
q: behaves strangely

### ISSUE THREAD

**Issue by hidjgr** [vscode-neovim/vscode-neovim#294] opened 2020-07-04 07:59 UTC
I'm not sure what happens but `q:` seems to actually put you in command editing mode but doesn't open a new window or dialog, and can't be exited with `:q` (it can however be exited with \<CR\>)

**Comment by asvetliakov** [comment] 2020-09-04 19:14
Ex command-line is not supported yet. I'm not sure it will be ever

**Comment by prwang** [comment] 2021-07-12 02:33
![image](https://user-images.githubusercontent.com/7418905/125222336-62134c80-e2fc-11eb-8711-848166505bfe.png)
Fortunately you can use context menu and paste from system clipboard, which is my 99% use cases of q: in Vim.

**Comment by theol0403** [comment] 2022-04-28 02:19
Duplicate of #505

**Closed by theol0403** 2022-04-28 02:19 UTC
Labels: enhancement
