### ISSUE TITLE
BufferManager: nvim_win_set_cursor: Cursor position outside buffer

### ISSUE THREAD

**Issue by David-Else** [vscode-neovim/vscode-neovim#498] opened 2021-01-01 20:44 UTC
Using the latest 0.0.73 I got this error when I came back to an unsaved file in normal mode. The cursor was frozen, then after moving around some other files and returning then it worked again.

```
2021-01-01T20:38:46.607Z BufferManager: nvim_win_set_cursor: Cursor position outside buffer
```
Not sure how to reproduce, but I thought I would post it as an issue in case anyone else got it.

**Comment by braxtons12** [comment] 2021-07-14 21:05
I also get this happening, but I haven't been able to reduce this to a reliably reproducible situation, as it seems kind of random.

It _seems_ that most of the time this happens when changing focus (with a mouse click) from an open editor to another one or the explorer, etc. is what triggers this, but it's inconsistent. Sometimes I can go 4 hours without it ever happening, sometimes it happens every 20 minutes. I've also had it happen when opening vscode and trying to immediately type in one of the restored/reopened editors from the last session.

I'm currently using version 0.0.82 and have experienced it on both Windows 10 and Ubuntu 20.10 and 21.04.

**Comment by achikin** [comment] 2022-02-01 13:45
The first time it happened was when I did View -> Editor layout -> Split in Group and then it followed every split/unsplit action until I restarted VSCode and then it has gone. Can't reproduce. 
```
VSCode Neovim 0.0.8.2
------------------------
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@BigSur

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.6.1/share/nvim"
-------------------------
MacOS 11.6
```

**Comment by Ahmad-Zaklouta** [comment] 2022-02-25 13:45
I am having the same issue all the time when I move between tabs.

**Comment by wenhao-eb** [comment] 2022-05-16 14:29
> I am having the same issue all the time when I move between tabs.

I have the issue in this same situation too.

**Comment by coderj001** [comment] 2022-05-25 11:22
I have same issue

```
NVIM v0.5.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az242-526

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by alexandru** [comment] 2022-06-05 08:23
I have the same issue, it happens frequently, and I haven't noticed any usage pattern that triggers it:

![image](https://user-images.githubusercontent.com/11753/172042037-b4690d84-eb8a-4a52-90f9-63f95bfe9243.png)

**Comment by zhiyuanzhai** [comment] 2022-10-18 13:47
When working with Jupyter in VSCode, and when I scroll around a notebook, this error occurs.

**Comment by zhourrr** [comment] 2022-11-16 02:15
> When working with Jupyter in VSCode, and when I scroll around a notebook, this error occurs. **EDIT**: not stably reproducing, either.

Same here

**Comment by fish895623** [comment] 2022-11-30 06:10
When I remove my $HOME/.local/share/nvim folder, it solved.
I think runtime dir make crash. I suggest replace to custom runtime path using rtp.

**Comment by theol0403** [comment] 2022-12-04 20:27
I get this sometimes too, but I don't know how to fix without reproduction steps.

**Comment by micimize** [comment] 2023-01-02 17:13
For reproduction, I got this pretty consistently initially because I had a keybinding collision using ctrl+n/p for navigation:
```json5
  {
    "command": "-vscode-neovim.send",
    "key": "ctrl+p",
    // "when": "neovim.mode != cmdline_normal"
  },
  {
    "key": "ctrl+p",
    "command": "workbench.action.previousEditorInGroup",
    // "when": "neovim.mode != cmdline_normal"
  },
  /* solution for my workflow was adding the comments above and this block.
  {
    "command": "-vscode-neovim.send",
    "key": "ctrl+n",
    "when": "neovim.mode != cmdline_normal"
  },
  {
    "key": "ctrl+n",
    "command": "workbench.action.nextEditorInGroup",
    "when": "neovim.mode != cmdline_normal"
  },
 */
 ```

**Comment by hermlon** [comment] 2023-01-04 16:49
I'm getting the same error when opening Jupyter Notebooks using the Jupyter Extension

**Comment by OldStarchy** [comment] 2023-06-28 04:23
I get this error a lot when editing settings.json with `"workbench.settings.useSplitJSON": true,`

**Comment by juanitorduz** [comment] 2023-07-19 15:42
Having lots of these warnings with the Jupyter Notebooks in VsCode :(

**Comment by xiyaowong** [comment] 2023-09-03 16:41
Can reproduce when the output panel is activated, but it is uncertain if there are any differences in the discussions under this issue.
![output](https://github.com/vscode-neovim/vscode-neovim/assets/47070852/dd24bca0-6b1c-4534-a3f9-af85606a51fa)

**Comment by theol0403** [comment] 2023-09-06 11:51
Hopefully this will be fixed in the latest release.

**Comment by hustrjh** [comment] 2023-09-06 15:12
@theol0403 I still encounter this issue since latest update. Here's how I reproduce it.
1. Make a global mark in current file. Press `mA` in normal mode.
2. Switch to another file and go back to mark A by pressing `'A`.
3. Then you can catch the issue.

I don't know whether it's the same issue as #1223 ?

**Comment by xiyaowong** [comment] 2023-09-06 15:29
obviously not

**Comment by xiyaowong** [comment] 2023-09-06 15:48
> @theol0403 I still encounter this issue since latest update. Here's how I reproduce it.
> 
> 1. Make a global mark in current file. Press `mA` in normal mode.
> 2. Switch to another file and go back to mark A by pressing `'A`.
> 3. Then you can catch the issue.
> 
> I don't know whether it's the same issue as #1223 ?

The error message is the same, but the reason is different.

**Comment by hustrjh** [comment] 2023-09-07 01:26
@xiyaowong I got it. Since mark is really useful, I hope this bug could be fixed either. Thanks a lot. 😀

**Closed** 2023-09-07 11:41 UTC
Labels: bug, need more info, manager: buffer, manager: cursor

**Comment by xTayEx** [comment] 2024-01-27 13:14
> I had this error until I assigned an 'affinity' to VSCode Neovim. I did this by clicking 'yes' in a warning message.
> 
> On v0.6.1 on macOS 13.6, after I reload the window, a new temporary file (eg. `Untitled-3`) pops up which has the contents of whichever file I was last on. In the temporary file I can use neo-vim shortcuts. Once I close the temporary file and go back to the original file I get 3 error messages and the warning about the 'affinity':
> 
>     1. `BufferManager nvim_set_current_win: Invalid window id: 1012`
> 
>     2. `CursorManager: nvim_win_set_cursor: Invalid window id: 1012`
> 
>     3. `CursorManager: nvim_win_set_cursor: Invalid window id: 1012`
> 
>     4. `Do you want to assign an Affinity to VSCode Neovim?`  -> Click yes on this message, may have to list all messages to see it.

Same error when i switch tab using <C-W><C-H>

**Comment by ibehnam** [comment] 2024-05-06 22:36
Any updates on this? This is very annoying and forces the user to quit VSC and open again.

**Comment by xiyaowong** [comment] 2024-05-07 01:09
> Any updates on this?

Any logs? 

> This is very annoying and forces the user to quit VSC and open again.

You can use `vscode-neovim.restart`

**Comment by ibehnam** [comment] 2024-05-07 21:20
@xiyaowong Sure, what kind of logs do you need? I can share them here.

**Comment by qomosoloto** [comment] 2024-05-09 14:48
Same issue, had to disable plugin.

**Comment by pbassut** [comment] 2024-07-16 21:27
Same issue here. Very annoying. For a brief moment I don't realize it and keep writing and it does all kinds of unexpected things that for some reason `u` can't undo.

**Comment by xiyaowong** [comment] 2024-07-17 00:03
@pbassut You can open a new issue and provide reproduction steps or a screen recording.

**Comment by lost22git** [comment] 2024-07-31 14:44
same issue, the best way to recover it is switch to another tab and back current tab
