### ISSUE TITLE
bug:  Output pannel  "vscode-neovim messages" automatically opens for using nvim plugings

### ISSUE THREAD

**Issue by Xinli-GUMP** [vscode-neovim/vscode-neovim#2056] opened 2024-06-02 05:14 UTC
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

v1.14.2

### Operating system/version

Windows 11 23H2

### Describe the bug

As the title, when I use nvim plugings such as sneaker, easy-motion, the output pannel will open automatically. It's annoying really!

![PixPin_2024-06-02_13-09-26](https://github.com/vscode-neovim/vscode-neovim/assets/95741155/2fb867a0-35ba-4894-a168-fd33542250b5)

### Steps To Reproduce

install plugings by neovim, and using in vscode-neovim

### Expected Behavior

output pannel "vscode-neovim messages"  shouldn't open automatically  just like logs.

**Comment by ollien** [comment] 2024-06-02 15:58
Duplicate of #2046. The intention was anything longer than two lines or when you get a "press return to continue" prompt, it would show up, to emulate real nvim, but I may have cast too wide a net. Will investigate

**Closed by ollien** 2024-06-02 15:58 UTC
Labels: bug
