### ISSUE TITLE
Random cursor behavior on large soft-wrapped text

### ISSUE THREAD

**Issue by albert-ying** [vscode-neovim/vscode-neovim#705] opened 2021-07-25 23:08 UTC
Attached is an example. I have a soft-wrapped paragraph in vscode, and when I keep holding `w`, it works fine at the first few lines. However, it will be stoped at a certain position. And if I use other motions like `b`, the cursor will just randomly jump. Also `vap` only highlights the first part of the paragraph. Any insight on what is happening here? Thank you!
https://user-images.githubusercontent.com/59846322/126916154-8fcd2fdd-78ea-4757-9776-b5762c564fc4.mov

p.s. I can replicate this after comment out all my initvim configurations

**Comment by vlwkaos** [comment] 2021-07-28 02:54
![image](https://user-images.githubusercontent.com/44766242/127256162-039111f5-e95b-4429-9295-387539253dcc.png)

Try with larger width. I think the extension limits the viewport due to performance reasons.

**Comment by albert-ying** [comment] 2021-07-28 19:04
Thank you! It seems to work!

**Comment by albert-ying** [comment] 2021-07-28 23:38
And I can still replicate it after comment out all the init.vim configuration.

**Comment by avenger0815** [comment] 2021-08-20 07:28
I seem to have the same issue, I cannot go past a certain line, the cursor seems to go further without showing as going up takes longer if I keep going down. Also marking code beyond that line does funny stuff. Unfortunately the plugin is completely unusable for me atm.
Ubuntu 20.04.3, pretty new install, no plugins to neovim.

**Comment by albert-ying** [comment] 2022-01-16 18:44
Neovim 0.61 still has this problem. Any update on this? As the 0.6 is the stable version now, this bug will affect anyone who uses it to write markdown document. Thank you!

**Comment by theol0403** [comment] 2022-04-30 04:02
Could this be fixed by #775?

**Comment by blackboardd** [comment] 2022-05-21 22:05
Going to be watching this as I've experienced a similar issue. I can jump to different places in the file just fine when I set the width to 10,000. However, when I use the visual select, the highlight is in the wrong place entirely. See attached.

![Screen Shot 2022-05-21 at 5 04 22 PM](https://user-images.githubusercontent.com/86866786/169670387-6469b788-f7ef-4cad-9d9a-b97dd0b09458.png)

**Comment by zbw8388** [comment] 2022-07-02 20:36
Highlighting in this extension is handled differently from cursor placement. For cursors, neovim directly provides the absolute column number via `win_viewport` message whereas highlights depends on relative column location (relative to the viewport). If we can get the viewport column offset, we can fix highlight issue on long lines.

**Comment by albert-ying** [comment] 2022-07-03 05:42
@zbw8388 I don't think visual mode is the root problem -- see attached random jump behavior:

You put the cursor at the end of the long-wrapped text, and toggle between the insert and normal mode. Then the cursor will just jump. No visual mode is involved.

https://user-images.githubusercontent.com/59846322/177026474-765e90da-743c-4212-85b9-36c00dfe3db4.mp4

**Comment by zbw8388** [comment] 2022-07-03 06:00
@albert-ying Sorry I was replying to @blackboardd 

What is the version of this extension you are using? Is this issue still occurring in the latest master branch?

**Comment by albert-ying** [comment] 2022-07-03 06:15
I think it is. I'm using v0.0.87, with NVIM v0.7.2 (basically the newest stable version). Could you replicate it @zbw8388?

**Comment by zbw8388** [comment] 2022-07-03 06:34
I cannot replicate it with the latest master branch. #775 changes cursor placement logic which might fix this issue.

**Comment by albert-ying** [comment] 2022-07-03 17:09
I just installed the current master branch (v0.0.88), and I can still replicate the issue.

Which neovim version did you use @zbw8388? This behavior only happens when the wrapped line is long enough

**Comment by zbw8388** [comment] 2022-07-09 20:12
Yes I can reproduce the issue. Sorry for the confusion! 

### Cause:

Neovim is defaulted to show only 1000 characters, and on long lines, that will start at some offset. However, vscode has no idea which offset it has. After doing the operation you described, neovim would center the cursor and tell vscode to go to column offseted at 500. Current implementation interprets that offset from column 0, and it causes the issue you observed. 

### Possible Fixes:
- Ignore `grid_cursor_goto` commands (which gives a relative column number) and rely only on `win_viewport` commands (which gives an absolute column number). 
  - However, this could not resolve issues related highlight, which has only relative column index 
- Use built-ins to get the correct offset: https://neovim.io/doc/user/builtin.html#winsaveview() 
- Wait for upstream to expose more apis: https://github.com/neovim/neovim/pull/15248

### Comments:
This issue only comes up when navigating using insert mode. If you use navigate using normal mode commands, neovim would combine multiple commands together and current implementation favors `win_viewport` over `grid_cursor_goto`. One temporary solution might be using normal mode commands to jump around the document. 

Nevertheless, the issue you raised in your first comment is resolved.

**Comment by albert-ying** [comment] 2022-07-09 22:49
Thank you for explaining the issue! Is there any plan to fix it? Although
the normal mode works fine, insert mode is inevitable if you really want to
edit the file...

Best,

Albert

**Comment by theol0403** [comment] 2022-07-20 05:51
Fixed by #971

**Closed by theol0403** 2022-07-20 05:51 UTC
