### ISSUE TITLE
[feature request] minimap support, scrollbar support

### ISSUE THREAD

**Issue by trusktr** [vscode-neovim/vscode-neovim#458] opened 2020-12-26 02:07 UTC
Thanks for this awesome plugin!

The idea is, for example, pressing `*` on a word, and if `hlsearch` is enabled then also showing the matches in the minimap and in the scrollbar.

It would be similar to VS Code's version where when the cursor is on a word it automatically highlights matches in the source code and those show up in the scrollbar (but apparently not in the minimap, don't know if that is possible).

**Comment by asvetliakov** [comment] 2021-01-03 21:00
This requires mapping visual selection to vscode selection. Unfortunately that requires additional api in neovim

**Comment by theol0403** [comment] 2022-08-09 16:52
Duplicate of #172

**Closed by theol0403** 2022-08-09 16:52 UTC
Labels: nvim api required
