### ISSUE TITLE
How to put the "command line popup window" on the bottom ?

### ISSUE THREAD

**Issue by gaoqiangks** [vscode-neovim/vscode-neovim#781] opened 2021-12-09 16:47 UTC
When I want to search something or execute a command, a popup window appears on the top. I mean this one in the following picture.  Is there any way to put this window on the bottom?

![2021-12-10 00-45-14屏幕截图](https://user-images.githubusercontent.com/52161883/145440396-73e60953-aa36-43c2-8f4c-f94b2ea4eca1.png)

**Comment by hackel** [comment] 2022-01-26 19:21
Not currently possible.  Please close this, it is a dupe of https://github.com/vscode-neovim/vscode-neovim/issues/297.

**Closed** 2022-01-26 20:39 UTC
