### ISSUE TITLE
Peek reference result unexpected auto open in new tab when selected

### ISSUE THREAD

**Issue by qwhcr** [vscode-neovim/vscode-neovim#635] opened 2021-05-11 16:18 UTC
When vscode-neovim plugin is enabled, merely selecting previously folded result will cause the reference location opening in new tab.

Step to reproduce:
init.vim: `nnoremap gr :call VSCodeCall("editor.action.referenceSearch.trigger")<CR>`,
type gr,
use arrow key to move between peek results,
unfold other results(reference results in other files will be folded at first) using either mouse or space(the default shortcut),
selecting any result in the now unfolded,
vscode automatically opens it in new tab.

Expected behavior:
when this plugin is disabled, doing the same selection operations in peek reference will not open the selection in new tab. I am able to normally select reference search result and view them in the peek window.

Why is this problematic:
Peeking feature is best used when we can see results in current tab. Automatically opening results in new tab is very disruptive. I effectively cannot normally peek references when I want to see references in other files(because the results will be folded and when i unfold and select them, the selection will immediately automatically open in new tab).

Example:

![](https://user-images.githubusercontent.com/32228070/117850170-e7657c80-b239-11eb-9e98-f1583f1417bb.png)

notice references in index.d.ts is folded.
now unfolding it.

![](https://user-images.githubusercontent.com/32228070/117850301-0532e180-b23a-11eb-9ec2-3a6adb778e00.png)

clicking or use arrow key to select the result in index.d.ts will automatically open the result in new tab. The expected behaviour is selecting the result in index.d.ts will only show the result in the peek window.

**Comment by qwhcr** [comment] 2021-05-11 16:22
![image](https://user-images.githubusercontent.com/32228070/117850170-e7657c80-b239-11eb-9e98-f1583f1417bb.png)
notice references in index.d.ts is folded.
now unfolding it.
![image](https://user-images.githubusercontent.com/32228070/117850301-0532e180-b23a-11eb-9ec2-3a6adb778e00.png)
clicking or use arrow key to select the result in index.d.ts will automatically open the result in new tab. The expected behaviour is selecting the result in index.d.ts will only show the result in the peek window.

**Comment by ATrackerLearner** [comment] 2021-05-25 13:40
Hi, same problem here, 

Steps to reproduce: 
- Go to a function, variable, class name and press F12 to get references
- Peek windows is open, I use arrow keys to unfold and I hover a reference 
- It automatically open the reference in tab at the current location of the cursor. It doesn't even move the cursor or the view on the reference. Also the cursor is stuck - I cannot apply any motion - I can switch to other mode (Visual, insert) and I can use command. Although, any command that requires the cursor to move does'nt work (such as / or ?) . I need to switch to another tab and return to the tab to "unstuck" the cursor.

Expected behaviour:
- Don't automatically switch to reference tab 
- No stuck cursor
- Switch cursor or/and view to the reference

Why is this problematic: 
It breaks the "Find references" feature on VSCode which is super useful.

Although, I would like to thank you for this amazing extension ! Good luck for maintenance and I hope this error will be fixed soon. 

Have a nice day,
Mathias.

**Comment by theol0403** [comment] 2022-04-29 03:50
Can't reproduce in latest version

**Closed by theol0403** 2022-04-29 03:50 UTC
