### ISSUE TITLE
VsCode mapping escape to kj directions unclear

### ISSUE THREAD

**Issue by Mosrod** [vscode-neovim/vscode-neovim#245] opened 2020-04-24 17:13 UTC
Keymaps.json should be:
```
[
    {
        "command": "vscode-neovim.compositeEscape1",
        "key": "k",
        "when": "neovim.mode == insert",
        "args": "k"
    },
    {
        "command": "vscode-neovim.compositeEscape2",
        "key": "j",
        "when": "neovim.mode == insert",
        "args": "j"
    }
]
```
for mapping kj to esc, instead of having the kk map be composite 2 and jj map being composite 1, as shown in the plugin description, shown below:

Enabling jj or jk as escape keys from the insert mode
Put into your keybindings.json:

for jj

    {
        "command": "vscode-neovim.compositeEscape1",
        "key": "j",
        "when": "neovim.mode == insert",
        "args": "j"
    }
to enable jk add also:

    {
        "command": "vscode-neovim.compositeEscape2",
        "key": "k",
        "when": "neovim.mode == insert",
        "args": "k"
    }

**Comment by shawntax** [comment] 2020-05-05 00:50
Why are the directions unclear? They explicitly describe how to map `jj`/`jk`, *not* what you are describing.

You can suggest to add a section for mapping `kk` / `kj`, but that'd be repetitive. Because once you understand how the first example works, you can figure it out (as you clearly did).

**Comment by oresk** [comment] 2020-06-05 17:19
I've just installed the plugin 5 min ago. Was using vim extension before.

Honestly I had no idea why does adding a k k shortcut end up with getting j k being another exit, and thought the instructions had a typo.

I usually use jj or kk to exit the insert mode.

**Comment by Mosrod** [comment] 2020-06-05 23:12
The format is a little hard to get used to, and it requires a lot of trial and error to get the intended result.

**Comment by javalight** [comment] 2020-09-25 11:24
Still have no idea how ti works, complete mystery.

**Comment by shawntax** [comment] 2020-09-27 20:16
> Still have no idea how it works, complete mystery. Would love more examples.

@javalight a wild opportunity to learn more about how something works because it's open-source appears! I'll help you get going.

Since we're working with keybindings, a good starting place is VSCode's [docs](https://code.visualstudio.com/docs/getstarted/keybindings), which describes the rule fields (`command`, `key`, `when`, `arg`).

The custom bindings define new commands, `vscode-neovim.compositeEscape1` and `vscode-neovim.compositeEscape2`, so let's search for that in the source code. When you find the right file, you'll see some functions like `handleCompositeEscapeFirstKey` and `handleCompositeEscapeSecondKey`. 

Those are key to understanding how the bindings work, so spend some time there. It could also be helpful, while studying those functions, to play around with the value of `arg` in each keybinding and see how the behavior changes.

**Comment by theol0403** [comment] 2022-04-28 00:38
Duplicate of #258. Refactoring the jk logic should come with more clear instructions.

**Closed by theol0403** 2022-04-28 00:38 UTC
Labels: documentation

**Comment by GladioFeng** [comment] 2023-12-28 03:38
@Mosrod awesome, it works.
