### ISSUE TITLE
bug: vscode-neovim crashes on cycling tabs

### ISSUE THREAD

**Issue by alexanfl** [vscode-neovim/vscode-neovim#2131] opened 2024-06-25 10:36 UTC
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

NVIM v0.10.0

### Operating system/version

Fedora 40

### Describe the bug

This bug first appeared a week or two ago. The problem is that when I cycle through tabs with either gt/gT or the ctrl+Tab, suddenly vscode-neovim crashes and I have to reload it. At first, I thought it just happened randomly, but I can reproduce 100 % of the time. I didn't see the error when I had 2-3 tabs open, but from 4 and up, I see it consistently.

Edit: It also happens "randomly". Seems like it crashes because it overloads for some reason?

### Steps To Reproduce

1. Cycle through tabs with gt/gT. I have to stop cycling to see the effect. After going through a handful of tabs, the extension stops and I'm either in perpetual insert mode or the cursor stops responding

### Expected Behavior

I can cycle through tabs without having to restart the extension.

**Comment by ian-h-chamberlain** [comment] 2024-06-27 15:01
When the extension crashes, do you see any error output or logs? I have been experiencing what I think is a similar issue on macOS running neovim 0.10.0, but I haven't been able to pinpoint what's causing it — it's possible it's due to changing tabs for me as well. I haven't see any log output or error popups, but maybe if I am able to set the log level higher I can catch something more useful.

In my case, I normally notice it when I switch back to VSCode from another application, and I rarely use `gt`/`gT` (favoring VSCode's ctrl-tab shortcuts). Calling `Neovim: Restart Extension` is usually enough to get around it, but it's definitely not ideal to have to restart all the time like this.

**Comment by alexanfl** [comment] 2024-06-28 11:30
> When the extension crashes, do you see any error output or logs? I have been experiencing what I think is a similar issue on macOS running neovim 0.10.0, but I haven't been able to pinpoint what's causing it — it's possible it's due to changing tabs for me as well. I haven't see any log output or error popups, but maybe if I am able to set the log level higher I can catch something more useful.
> 
> In my case, I normally notice it when I switch back to VSCode from another application, and I rarely use `gt`/`gT` (favoring VSCode's ctrl-tab shortcuts). Calling `Neovim: Restart Extension` is usually enough to get around it, but it's definitely not ideal to have to restart all the time like this.
> 
> Edit: maybe also sometimes caused by VScode's `View: Reopen Closed Editor` command?

Thanks for the reply! From what I see now, it definitely seems to be related to upgrading to neovim 0.10. I just downgraded to 0.9.5 and was not able to reproduce the error. I tried to check the logs, but the problem is that the Neovim errors/messages in Output disappear when the extension crashes. Is there a way I can see them after restarting the plugin, or somewhere else?

For now, I think I will stay on 0.9.5 since that seems to solve the issue for me.

**Comment by ian-h-chamberlain** [comment] 2024-06-28 18:22
Hmm, I switched to 0.9.5 but I'm still experiencing the issue sometimes — maybe it's something different then, or different between OSes?

For the log level, I learned you can set it persistently with this button (not very discoverable, VSCode!):

![Screenshot 2024-06-28 at 14 18 34](https://github.com/vscode-neovim/vscode-neovim/assets/11131775/925c6e79-9d6d-494f-b7a1-1a30e308bf96)

I'll post again here if I can capture debug logs next time it happens, but I did see some warnings this time:
```
2024-06-28 11:00:21.831 [warning] ViewportManager: Unable to update scrolled view. No grid for winId: 1066
2024-06-28 11:00:37.515 [warning] ViewportManager: Unable to update scrolled view. No grid for winId: 1067
2024-06-28 11:00:50.132 [info] MessagesManager: 13 fewer lines
2024-06-28 11:00:50.133 [info] MessagesManager: 13 fewer lines
2024-06-28 11:01:16.890 [warning] ViewportManager: Unable to update scrolled view. No grid for winId: 1068
2024-06-28 11:01:17.498 [warning] ViewportManager: Unable to update scrolled view. No grid for winId: 1069
2024-06-28 11:01:18.539 [info] MessagesManager: 1 more line; before #84  1 second ago
2024-06-28 14:15:03.939 [warning] ViewportManager: Unable to update scrolled view. No grid for winId: 1070
```

In this case, the most recent warning did occur around the time the extension stopped working, so maybe that's a clue about what's happening?

**Comment by xiyaowong** [comment] 2024-06-29 06:03
This should be a Neovim issue, vscode-neovim does not use any experimental APIs or ffi. Also, recently, there have been quite a few reports of crashes with Neovim.

**Comment by ian-h-chamberlain** [comment] 2024-06-29 13:46
Hmm, if it was a Neovim crash we would expect to see an error pop up with `Neovim exited:` or `Neovim was disconnected`, right? I have seen those occasionally when using a nightly neovim version. That would also make it easier to restart with the button shown in the popup...

**Comment by xiyaowong** [comment] 2024-06-29 16:19
> Hmm, if it was a Neovim crash we would expect to see an error pop up with `Neovim exited:` or `Neovim was disconnected`, right?

Yes

**Comment by ollien** [comment] 2024-06-30 19:50
This is a duplicate of #2000. On macOS, I found the easiest solution was to just download an 0.9.5 binary to /opt and point `vscode-neovim.neovimExecutablePaths.darwin` to the downloaded binary. 

It's unfortunate, but this is an upstream problem

**Comment by ian-h-chamberlain** [comment] 2024-06-30 22:38
Ok, last night I was reproducing this more consistently, on both `0.9.5` and `0.10.0`. Here are some of my notes about it, maybe they will help:

* No error message / notification is displayed when the problem occurs. Most of the time I was simply stuck in normal mode and unable to move the cursor or change modes, etc. 
  * In one case, I was stuck in macro-recording mode.
  * I have seen insert-mode before, but not typically
* Keybinds become unresponsive, but the extension is still active (logging, etc.) and the `neovim` process is still running:
   ```
   0.0  0.4  0:51.00 │  ├─ /Users/ianchamberlain/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --type=utility --utility-sub-type=node.mojom.NodeService --lang=en-US --service-sandbox-type=none --dns-resu
   0.0  0.1  0:00.00 │  │  └─ /opt/homebrew/bin/nvim -N --embed --cmd source /Users/ianchamberlain/.vscode/extensions/asvetliakov.vscode-neovim-1.17.2/runtime/vscode-neovim.vim
   ```
* `Developer: Toggle Keyboard Shortcuts Troubleshooting` showed it was still running `vscode-neovim.send` when pressing e.g. `hjkl`, so the context keys must have been set as for normal mode.

Extension logs (I believe the problem started around `2024-06-30T03:15:23.949Z`): [vscode-app-1719717602613.log](https://github.com/user-attachments/files/16046393/vscode-app-1719717602613.log)

Reproduction steps that were working for me almost 100% of the time, but don't seem to be working anymore. I'm not sure what changed, but this is basically what I had at the time:
1. 10-15 tabs open total, including several `:help` tabs (external buffers) 
2. search for phrase in workspace using VSCode shortcut (<kbd>cmd+shift+f</kbd> on macOS)    3. click a search result that opens a new editor (buffer that was not previously open)
4. click in the new editor
5. Observe stuck cursor / unresponsive, run `Neovim: Restart Extension` to go back to step 1

I don't have too many other clues yet, but maybe there's something there that helps... I'll keep trying to figure it out!

**Comment by xiyaowong** [comment] 2024-07-01 00:04
Alright, then the title of this issue is completely incorrect.

**Comment by xiyaowong** [comment] 2024-07-01 00:27
@ian-h-chamberlain I can't reproduce the issue. From the logs, it seems that the problem is in the `syncEditorLayout` function.

https://github.com/vscode-neovim/vscode-neovim/blob/08e973d20e93835416c3c5a7bd3a81239c02d213/src/buffer_manager.ts#L539

You can add logs to see where it is getting stuck.

**Comment by ggsggs** [comment] 2024-07-01 09:54
The extension also crashes for me. I used the `clean` option, but it also crashes with the option enabled.
Using MacOS Sonoma and Neovim 0.10.0. Latest extension and VSCode stable versions.

 I use CTRL/^ + Tab to switch between open files. I use Jupyter Notebooks and .py files to switch from and to. It also crashed using the Mouse to change tabs.
 
 I mostly do remote dev via VSCode-SSH.

**Comment by xiyaowong** [comment] 2024-07-01 11:30
There are now two situations: 

1. Neovim crashes and an error popup appears.

- #2000
- #2057
- #2076

2. vscode-neovim becomes unresponsive and freezes.

**Comment by alexanfl** [comment] 2024-07-01 13:07
So looks like a duplicate of #2000

**Comment by alexanfl** [comment] 2024-07-01 13:26
Tested the nightly neovim 0.11.0 and still disconnects.

**Comment by ggsggs** [comment] 2024-07-01 15:51
@xiyaowong thank you, I looked at the linked issues. It might have been Copilot's fault.
I disabled Copilot altogether, I wasn't interacting with it or the Copilot chat at all so didn't think it was related.
Now the crashes have stopped (or at least not that frequent).

Do you have the `Github Copilot` extension installed/enabled? @ian-h-chamberlain @alexanfl

**Closed** 2024-07-06 05:38 UTC
Labels: bug, upstream
