### ISSUE TITLE
bug: Use 'o' to a new line, but the indentation in this new line will not deleted after pressing <enter>

### ISSUE THREAD

**Issue by Old-Farmer** [vscode-neovim/vscode-neovim#2288] opened 2024-10-16 03:54 UTC
### Check the following:

- [X] I have tried setting `vscode-neovim.neovimClean` in VSCode settings and **restarting VSCode.**
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing (closed!) issues.

### Neovim version (nvim -v)

0.10.1

### Operating system/version

Linux Mint 21.3

### Problem (including [log messages](https://github.com/vscode-neovim/vscode-neovim?tab=readme-ov-file#troubleshooting))

When I use 'o' to a new line, and then press \<enter\>. The indentation in this new line will not deleted after pressing \<enter\>.

The normal behavior in neovim is that the indentation will be deleted if the indentation is generated auto && the line doesn't have non-blank characters.

The normal behavior in vscode is that the indentation will be deleted if the line doesn't have non-blank characters.

![image](https://github.com/user-attachments/assets/901e1010-eb89-4d8c-8fe4-1be40cb31cdc)

### Steps To Reproduce

1. A normal file with a line indented.
2. cursor to this line and press 'o'
3. press \<enter\>

### Expected Behavior

The new line created by 'o' will get empty if I press \<enter\> to create another new line below it.

**Comment by justinmk** [comment] 2024-10-16 09:34
Duplicate of https://github.com/vscode-neovim/vscode-neovim/issues/2250

**Comment by Old-Farmer** [comment] 2024-10-16 10:44
> Duplicate of #2250

I really don't think they are the same issue.

**Comment by justinmk** [comment] 2024-10-16 10:59
> The normal behavior in neovim is that the indentation will be deleted if the indentation is generated auto && the line doesn't have non-blank characters.

what is the normal vscode behavior?

**Comment by xiyaowong** [comment] 2024-10-17 00:18
It cannot be achieved. The 'o' operation syncs the modifications in nvim to vscode, and vscode retains this modification. You can try the following trick:

```lua
vim.keymap.set('n', 'o', function()
  require('vscode').action('editor.action.insertLineAfter', {
    callback = function()
      vim.cmd.startinsert({ bang = true })
    end,
  })
end)
```

**Closed by xiyaowong** 2024-10-17 00:18 UTC
Labels: bug, category: sync
