### ISSUE TITLE
Inserts extra characters in Escape.

### ISSUE THREAD

**Issue by kingedward35** [vscode-neovim/vscode-neovim#540] opened 2021-01-26 03:26 UTC
I have been seeing this issue recently where when I escape from insert mode to normal mode, the cursor will add extra characters to the end and sometimes the beginning of a line. It doesn't happen all the time, but often enough that I have tried to see if anyone knows of a fix. Here is a screenshot of what it looks like: 
![image](https://user-images.githubusercontent.com/12418717/105796128-649b0900-5f4b-11eb-9ed8-4b5ffee41743.png)

I am currently using the latest neovim nightly (as of a few minutes ago) and v0.0.78 of the vscode plugin. If anyone has any tips how this might be solved, I would greatly appreciate it.

**Comment by nrdlab** [comment] 2021-04-03 23:00
Same here with: 
```sh
v0.0.78
```
and 
```sh
NVIM v0.5.0-dev+1211-g6db3ba9df
Build type: Release
LuaJIT 2.1.0-beta3
```
![image](https://user-images.githubusercontent.com/16638949/113493618-33a5fa00-94e1-11eb-9a78-ed4357c7b29e.png)

**Comment by nrdlab** [comment] 2021-04-04 13:56
seems like it happens mostly by hitting escape after typing special chars though
```sh
< >  " "  ' '  { } () 
```

**Comment by nrdlab** [comment] 2021-04-18 08:17
just discovered that this issue happens only with `v0.0.78` 
previous versions are working fine 
@asvetliakov

**Comment by Antyos** [comment] 2021-06-14 18:36
I can confirm this issue with:
```
Neo Vim: v0.0.081
```
and
```
NVIM v0.5.0-dev+1055-g8950f4e94
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

If I were to guess, it has something to do with VSCode and Neo Vim fighting over auto-closing characters. While the characters noted by @nrdlab seem to be a consistent way to cause the issue, I have had the issue happen with other characters, including new lines and deletions, in no repeatable manner.

It is incredibly annoying and makes the extension borderline unusable.

**Comment by theol0403** [comment] 2021-06-14 20:57
I cannot reproduce this issue. 

- did you try with empty init.vim 
- do you have any vim auto-closing plugins
- what is your `editor.autoClosingQuotes` setting?
- do you have any vscode auto-closing extensions

**Comment by Antyos** [comment] 2021-06-20 23:11
@theol0403 I tried everything I could think of to isolate the issue with no success. Including:

- Disabling all other extensions
- Disabling `init.vim` and deleting (temporarily renaming) my entire `~\AppData\Local\nvim\` folder
- Removing default VS Code settings / keybindings
- Disabling all VS Code editor closing settings

My VSCode settings currently look like this:

```json
{
    "vscode-neovim.neovimExecutablePaths.win32": "C:\\tools\\neovim\\Neovim\\bin\\nvim.exe",
    "editor.autoClosingBrackets": "never",
    "editor.autoClosingDelete": "never",
    "editor.autoSurround": "never",
    "editor.autoClosingOvertype": "never"
}
```

I can then open a plain text file, enter insert mode, and type:

```plaintext
test()
```

But after hitting escape, I get:

```plaintext
test()test()
```

Unless I hit `u` (undo), at which point, it goes back to how I typed it. If `editor.autoClosingBrackets` is enabled, the extra `test()` is placed inside the parentheses.

One thing of note is that although I have experienced all of the characters that @nrdlab noted, I only got the issue with:

```
( ) [ ] { }
```

It could be a bug with an older version of Neovim. I am currently running on the latest pre-release version installed via Chocolatey, but I know there are more recent versions that have just seemed a bit more intimidating to install.

**Comment by theol0403** [comment] 2021-06-21 04:19
@Antyos Thanks for the detailed report. I have no idea what is wrong, I can only suggest trying a newer version of neovim.

Have you by chance tried to build the extension yourself? It's possible that a patch you made which differs from the officially released version causes the issue? One mistake that is easy to make is that vscode uses a cached version of the plugin even if you uninstall it - uninstalling and then installing from the marketplace will still use your local build of the same version number.

**Comment by Antyos** [comment] 2021-06-21 06:28
I have more information to add to the weirdness that is this issue:

- I run VS Code on a laptop with a docking station. When undocked, I cannot repeat the issue. When docked (using another keyboard and mouse), I always get the issue.
- I updated to nvim v0.5.0-dev+1429-gb585f723b (most recent as of an hour ago). This did not fix the issue.
- Since updating my installation of nvim, the issue cannot be repeated on files that have never been saved, i.e. doing a `ctrl+n` to open a new blank file
- About 1 out of 5 times when typing `test()` or `foo()` in a file, I don't get the issue. This is more frequent if it is the first thing I type when switching to a file, but not always.
- The issue does not occur when recording a macro. I also noticed that the parentheses did not auto-close either, but I already noted that `editor.autoClosingBrackets` isn't the issue.
- I thought it might have something to do with the suggestions box popping up. I set `editor.quickSuggestionsDelay` to a really large number to avoid the popup, but it didn't help. That doesn't mean the suggestions aren't related, but it doesn't mean the are either.

I have not had a chance to build the extension myself, but I may try that if I get a chance tomorrow.

Something also worth noting, I have never had this issue when using Neovim on its own (via a terminal); only when using it through VS Code.

**Comment by Antyos** [comment] 2021-09-12 03:01
I recently had to reinstall Windows on my computer (which has become all too common for me). When I put VSCode and NeoVim back on my computer, I found that I was no longer experiencing this issue!

While I don't suggest reimaging your computer for this reason, it may be worth uninstalling the extension (and making sure the extension files are really gone under `%userprofile%\.vscode\extensions\`, and reinstalling the extension. I feel a bit dumb for not thinking of trying that earlier.

**Comment by ryanalta** [comment] 2021-12-17 17:33
I think this is a conflict between any extensions neovim has included and VSCode autocomplete/suggestion behavior. I seem to have noticed less of this behavior when I disable more of VSCode's auto closing stuff, but it still doesn't completely fix it. It seemed to happen for me without fail with more complex syntaxes like Vue, which has JS/TS, CSS, and XML all in one file.

But, disabling pretty much all plugins, syntaxes, everything in Neovim and being careful about what I enable, as well as upgrading to neovim 0.6.0 seems to have fixed the problem, even in the more complex Vue files. It could also be worth making sure that if you use Neovim with Python enabled, you're only using Python3, and have the latest of everything else. Really seems to be an issue where neovim gets a little slow and causes conflicts, not as much of a problem with the VSCode plugin itself (reinstalling that didn't help for me).

**Comment by theol0403** [comment] 2022-04-29 01:34
Closing as I still can't reproduce.

**Closed by theol0403** 2022-04-29 01:34 UTC

**Comment by LawrenceLiu023** [comment] 2024-09-05 10:05
Same issue with Neovim v0.10.1, vscode-neovim v1.18.9, vscode v1.92.2， ubuntu v20.04.2. When I input `(`, `)`, `[`, `]`, `{`, `}` before switching to normal mode, what I entered in insert mode will be repeated.

**Comment by xiyaowong** [comment] 2024-09-05 10:23
> Same issue with Neovim v0.10.1, vscode-neovim v1.18.9, vscode v1.92.2， ubuntu v20.04.2. When I input `(`, `)`, `[`, `]`, `{`, `}` before switching to normal mode, what I entered in insert mode will be repeated.

@LawrenceLiu023 With `vscode-neovim.neovimClean` enabled?

**Comment by abhijithanandan** [comment] 2024-10-16 20:33
I am facing this same issue on version 1.18.13. It has made the plugin unusable. I tried everything suggested in the discussion here but was still unable to resolve it. I'm on Ubuntu 22.04.5, nvim v0.11.0-dev-965+gfb74fd295  and vscode 1.94.2. Tried downgrading versions and removing other plugins, init.vim etc... the problem still persists. I can provide any further info for debugging if requested.

**Comment by theol0403** [comment] 2024-10-16 21:06
@abhijithanandan removing init.vim is not enough, make sure you try with neovimClean

**Comment by abhijithanandan** [comment] 2024-10-16 21:36
Thank you, it is working. But all the Neovim plugins are now disabled. Is there a way to fix that?

**Comment by alps2006** [comment] 2025-01-02 10:34
I reviewed the source of vim-matchup, and the configuration can resolve the issue described below.

```lua
      -- Deferred highlighting improves cursor movement performance
      -- and fix vscode-neovim inserting extra characters in escape.
      vim.g.matchup_matchparen_deferred = 1

```
