### ISSUE TITLE
C-f/C-b do not do page down/up

### ISSUE THREAD

**Issue by f-squirrel** [vscode-neovim/vscode-neovim#1072] opened 2022-11-02 15:10 UTC
How to reproduce:

Prepare a few display's long text file. 
**C-f**
* go to the top of the file (`gg`)
* Page down (`C-f`) ==> jumps to the beginning of the next page (in my case +40 lines)
* Page down (`C-f`) ==> **jumps to the next line**
* Expected: jump again for 40 lines

**C-b**
* go to the end of the file  (`G`)
* Page up (`C-b`) ==> jumps 38 lines up
* Page up (`C-b`) ==> jumps 5 lines up
* Expected: jump the same amount of lines backward and forward until reaches BOF/EOF.

It may be related to https://github.com/vscode-neovim/vscode-neovim/issues/983.

**Comment by theol0403** [comment] 2022-11-12 23:19
Duplicate of https://github.com/vscode-neovim/vscode-neovim/issues/1064

**Closed by theol0403** 2022-11-12 23:19 UTC
