### ISSUE TITLE
bug: Composite escape keys not working when recording a macro

### ISSUE THREAD

**Issue by Mateuscvieira** [vscode-neovim/vscode-neovim#2138] opened 2024-07-03 18:06 UTC
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

1.18.0

### Operating system/version

Windows 10

### Describe the bug

When trying to record a macro that inserts something, I can't use my composite escape keys "jk" and "kj". I have checked and setting only one of the options (either jk or kj) does not fix the issue.
An interesting detail is that the editor somehow still recognizes that a composite escape key sequence is starting, as it lags behing if I type those keys. But right after I press the second one, it types it normally instead of escaping.

### Steps To Reproduce

1. Start a macro with q<a-z>
2. Enter insert mode
3. Attempt to escape with the composite escape key

### Expected Behavior

The expected behavior is escaping the same way both when recording a macro and when not.

**Comment by xiyaowong** [comment] 2024-07-03 23:17
Duplicate of #1959

**Closed by xiyaowong** 2024-07-03 23:17 UTC
Labels: bug
