### ISSUE TITLE
ctrl-e and ctrl-y won't update the cursor position when it is out of the editing window.

### ISSUE THREAD

**Issue by southp** [vscode-neovim/vscode-neovim#149] opened 2020-01-13 03:12 UTC
## Summary
First of all, sorry that I don't know the exact terms for what I'm trying to describe, so hopefully I can still get my points across.

When on a native neovim, we can scroll the editing window upwards/downwards for one line by ctrl-e/ctrl-y, without changing the cursor position. When the editing window goes beyond the cursor position, it will "push" the cursor along with the boundary. However, on vscode-neovim, the cursor will always stay at the same position, disregards the window. Please refer to the screencasts below for clearer demonstration.

I'd love to work on a patch if you can help me with some pointers :)

## Expected result
Here is what happened in a native neovim:
![demo-cursor-expected](https://user-images.githubusercontent.com/1842898/72231259-75edcd80-35f5-11ea-8db3-4516e9543a0e.gif)

## What happens instead
Here is what happened in vscode-neovim:
![demo-cursor-issue](https://user-images.githubusercontent.com/1842898/72231264-7ab28180-35f5-11ea-9acd-0f2948d10b51.gif)

**Comment by asvetliakov** [comment] 2020-01-13 03:37
Should be easy as [uncommenting/revisiting these lines](https://github.com/asvetliakov/vscode-neovim/blob/21ba0eb0ac483f45d73fb1333e46ae3178e4448d/src/controller.ts#L640-L708). The jumplist note is no longer relevant. There should be an option to toggle old behavior

**Comment by nwaywood** [comment] 2020-09-12 10:55
@asvetliakov since you say that uncommenting the lines to make this work will no longer break the jumplist, any chance they could be uncommented for the next release?

**Comment by Shatur95** [comment] 2020-09-12 11:01
@nwaywood, try it yourself to help us to improve the plugin. The file was moved [here](https://github.com/asvetliakov/vscode-neovim/blob/00d594e0ca7d3c15fe7ca84e52b878d38f735f2c/src/cursor_manager.ts#L444). Uncomment, build the extension and test. If it works - sand a PR.

**Comment by nwaywood** [comment] 2020-09-12 11:25
@Shatur95 thanks for the link to the new file location. I would be more than happy to test and submit a PR for this. However I have zero experience with developing VSCode extensions and the readme for the project doesn't have any instructions on how to build/run a local version of the extension. 

I am assuming that to build I would just need to run this https://github.com/asvetliakov/vscode-neovim/blob/master/package.json#L1073. But then how do I get vscode to use the local version?

**Comment by Shatur95** [comment] 2020-09-12 11:31
@nwaywood, I very new even for TS, but let me try to help you:

1. Download the repo.
2. Open the project folder in VSCode.
3. Execute `yarn install` in terminal. (you should have `yarn` installed via `npm`)
4. Run the project.

You will have a new instance of VSCode with local version of the plugin available for debugging.

If you want to build it and test for daily use, then you need to install `vsce` via `npm`. Then just run `vsce package` in the project folder.

**Comment by nwaywood** [comment] 2020-09-13 03:59
@Shatur95 I'm not sure how to do step 4, there is no "run" script in the `package.json` file

**Comment by Shatur95** [comment] 2020-09-13 07:24
@nwaywood, I meant execute "Run: Start without debugging" or "Debug: Start debugging" from command palette in VSCode.

**Comment by nwaywood** [comment] 2020-09-13 09:33
After doing some coding today I have noticed that this issue doesn't happen all the time. I haven't been able to figure out how to reliably reproduce this bug. I'll pay attention to what I did next time it happens and hopefully will be able to reproduce it so I can test.

**Comment by theol0403** [comment] 2022-07-31 07:04
Should be fixed in latest master

**Closed by theol0403** 2022-07-31 07:04 UTC
Labels: enhancement, help wanted
