### ISSUE TITLE
$1000 bounty for lightspeed support

### ISSUE THREAD

**Issue by andyljones** [vscode-neovim/vscode-neovim#804] opened 2022-01-18 18:30 UTC
I'd like to be able to use [lightspeed](https://github.com/ggandor/lightspeed.nvim) with vscode-neovim and I'm willing to pay $1000 (edit: prev $500) to whoever implements it. My amateur take is that this'll involve adding support for extmarks, though I may well be wrong about that. 

I've previously emailed @asvetliakov with the offer and not heard back, so figured I'd offer it openly. I was also gonna email @theol0403 but I couldn't find any way to contact him privately.

**Comment by asvetliakov** [comment] 2022-01-18 18:38
>I've previously emailed @asvetliakov with the offer and not heard back, so figured I'd offer it openly
Sorry, i probably missed your email. Anyway, i don't have any time for this right now, but great offer btw. This should be really relatively simple - just need to replace HL/extmarks call with the plugin one, like this:
https://github.com/asvetliakov/vim-easymotion/blob/34fb922c3cf5e88cff3f0824005e219dce83ea6f/autoload/EasyMotion.vim#L1046-L1054

**Comment by andyljones** [comment] 2022-01-18 21:29
Thanks Alexey! Do you happen to know anyone else who might be keen to implement this? I've been wondering where else might be best to promote this.

**Comment by theol0403** [comment] 2022-01-18 21:41
Thanks for the offer! I'm very busy, but I'd be willing to take a shot. I'll find a time to look into this a bit later this week. Thanks

**Comment by theol0403** [comment] 2022-01-19 22:17
Alright so I can think of 3 general ways to do this:
- use some (theoretical) nvim notification api to properly render extmarks. Last I checked neovim does not send a notification when extmarks are updated, but things could have changed or I could have missed it. This is the ideal, most general solution.
- override the lua api commands with a custom command that communicates directly to vscode. Still fairly general, and would also enable support for hop.nvim and also possibly be a way to refactor this extension in general (redirect the neovim lua api to vscode commands). This might be a good solution to add support for many other neovim plugins. However, interfering with the api might cause some problems and implementing the api might be a lot of work. I guess it probably won't be much work for this usecase though, but I'd rather take the opportunity to make this general. Maybe intercepting the nvim commands but then still forwarding to nvim would be acceptable.  
- edit the lightspeed backend to communicate directly with vscode, like was done for easymotion. This isn't a very clean solution.

I'll investigate these more a bit later today.

**Comment by kohane27** [comment] 2022-01-28 17:28
@theol0403 thank you very much for looking into this issue. I desperately want to use lightspeed as well. I eagerly await your update. Thank you again!

**Comment by trkoch** [comment] 2022-02-03 09:25
@theol0403 Is this perhaps at least remotely related to https://github.com/vscode-neovim/vscode-neovim/issues/543? Just checking.

**Comment by theol0403** [comment] 2022-02-05 22:42
Hey, sorry for the delayed response.

I have good news and bad news.

The good news:

Lightspeed already works 70% out of the box. The label highlighting works well, and mostly everything seems to just work. The main thing that is broken is that the label text isn't being applied. 

Properly implementing first-class extmark support is possible using the nvim api, using https://neovim.io/doc/user/ui.html#ui-event-grid_line `text` field. The extension is already aware of the hint text here: https://github.com/vscode-neovim/vscode-neovim/blob/b9def15f267d0e212c989981c883741de4256993/src/highlight_provider.ts#L261.

All that is required is to implement functionality that applies the text onto the vscode decoration for the highlight. After that, all the heavy lifting is done by neovim and vscode.

There are a couple other small issues, like overwin support, and the cursor isn't hidden in lightspeed mode (and the fake cursor isn't shown), but those are probably easy fixes.

The bad news:

Doing so likely requires a rewrite of the highlight provider to support "text highlights", which would likely be non-trivial. Given my limited knowledge of typescript and vscode internals, it would take me quite a bit of effort to learn and implement this. I am still interested, and I am also motivated by having lightspeed support, but I need to find time for me to really dedicate towards this. 

And unfortunately, I am currently dealing with 7 full engineering courses at university and don't have that kind of time until later in the spring or the summer. If this still isn't address by then, I'll take another shot. Also, it's possible I'll occasionally spend some time on this before then.

I'm not interested in implementing the same patch as Alexey did with easy easymotion, because then all the highlighting lightspeed does will also need to be re-implemented, and there will still be no first-class extmark support. 

If anyone else wants to tackle this, they are of course welcome.

**Comment by andyljones** [comment] 2022-04-09 16:16
Upped to $1000.

**Comment by windwp** [comment] 2022-04-21 00:30
@andyljones I will take this.
can you give me an email  I will send you a solution :)

**Comment by andyljones** [comment] 2022-04-21 00:34
> @andyljones I will take this. can you give me an email I will send you a solution :)

🎉 me@andyljones.com . To be clear, it has to be fully functional to get the bounty.

**Comment by theol0403** [comment] 2022-05-19 17:13
Merged!

**Closed by theol0403** 2022-05-19 17:13 UTC

**Comment by andyljones** [comment] 2022-05-19 17:29
Amazing! @windwp , what address can I contact you on?

**Comment by andyljones** [comment] 2022-05-19 17:39
@theol0403 Have you got an email I can contact you on too?

**Comment by theol0403** [comment] 2022-05-19 18:46
> @theol0403 Have you got an email I can contact you on too? The bounty's entirely windwp's, but I'd like to pay out a little extra for the work you've done reviewing this and getting it merged.

Thanks! You can contact me at theol0403@gmail.com

**Comment by windwp** [comment] 2022-05-19 23:58
@andyljones https://paypal.me/trieule1vn
i will donate back to @theol0403  and @asvetliakov   100$.

**Comment by andyljones** [comment] 2022-05-20 00:11
Paid!

**Comment by windwp** [comment] 2022-05-20 03:30
Thank i got it

**Comment by chrisands** [comment] 2022-05-28 16:11
I've got delay when press `s` in vscode using lightspeed, but I don't have delay when press `shift+s` or use lightspeed in terminal nvim. Maybe you could help me with delay?
cc @windwp @andyljones

**Comment by fpiem** [comment] 2022-06-01 13:29
Hi @andyljones,
First off, thank you for your work! I love being able to use lightspeed in VSCode.

I came across an issue when testing this extension. Look at the image below (left is VSCode, right is native Neovim running in the VSCode terminal). From line 126, i type `sSp`, wanting to get to the `... <Space>` at line 140. In Neovim, my cursor appears appears on the correct position, in VSCode it does not. The VSCode cursor *is* in the correct position (if I type `l` I end up on the p correctly) but it is being drawn in the initial position.

![Screenshot from 2022-06-01 15-25-19](https://user-images.githubusercontent.com/77389987/171415284-c6f720e1-4df3-4a7a-96c1-38edecf0914e.png)

Same thing happens if I press `sin + s` (the last `s` is the lightspeed guide), wanting to get to "insert" on line 127, the cursor doesn't move in VSCode, but does in Neovim:

![Screenshot from 2022-06-01 15-27-03](https://user-images.githubusercontent.com/77389987/171415629-872db1be-0582-4d26-8a50-b25c926a4815.png)

Again, the VSCode cursor *did* move, it's just not being drawn in the new position.

Would it be possible for you to take a look at this issue or suggest a way to fix it? Any help would be greatly appreciated!

**Comment by theol0403** [comment] 2022-06-01 14:54
> Again, the VSCode cursor *did* move, it's just not being drawn in the new position.
> 
> Would it be possible for you to take a look at this issue or suggest a way to fix it? Any help would be greatly appreciated!
>  

https://github.com/vscode-neovim/vscode-neovim/pull/868#issuecomment-1131963354

**Comment by fpiem** [comment] 2022-06-06 12:51
Thank you, but where should the `patch_lightspeed.lua` be placed?

**Comment by echaya** [comment] 2022-06-19 13:20
@theol0403 hey mate, just checking if the latest plugin supposes to support https://github.com/ggandor/leap.nvim as well or just lightspeed by design? 

> It is essentially a streamlined version of [Lightspeed](https://github.com/ggandor/lightspeed.nvim), with a focus on simplicity, sane defaults, and maintainability

**Comment by varunbpatil** [comment] 2022-07-15 16:44
@theol0403 , Is the `patch_lightspeed.lua` still required? If yes, where/how should the patch be applied?

**Comment by theol0403** [comment] 2022-07-19 04:49
Currently, it is still required for more optimal jumps. Currently, lightspeed provides jumps for 200 lines of code, when the viewport is usually around ~100. It also does not respond to *mouse* scrolling in vscode.

Merge it with `require('patch_lightspeed)` after putting the file next to your init.lua.

**Comment by theol0403** [comment] 2022-07-31 02:20
@andyljones the PRs recently merged into master significantly improves lightspeed/leap support!

Now the viewport syncs with neovim, so that lightspeed knows exactly which lines are on the screen, and some highlight issues were fixed.

**Comment by tbenthompson** [comment] 2022-08-17 20:59
This is awesome. Thanks everyone for all the work!

@theol0403 with the new PRs, are the suggestions in your comment here (https://github.com/vscode-neovim/vscode-neovim/pull/868#issuecomment-1131963354) still necessary? Only a subset of those suggestions?

**Comment by theol0403** [comment] 2022-08-19 17:48
@tbenthompson no more suggestions needed to get it working. However, there are some PRs still in master that will help with lightspeed accuracy by properly telling it the vscode viewport height.
